/**
 * Handle squatting/impersonation guard (docs/SOCIAL.md §11, D7): an obvious
 * app-terms list plus a short list of major distillery/brand names, reserved
 * at launch. Not a 500-name curation project — expand on demand, when someone
 * actually tries. Handles are compared already-normalized (normalizeHandle:
 * lowercase, trimmed), so every entry here is lowercase with no separators.
 */

const APP_TERMS = [
  "admin",
  "administrator",
  "whaikey",
  "support",
  "help",
  "api",
  "about",
  "settings",
  "sharing",
  "friends",
  "notes",
  "bottles",
  "bottle",
  "pour",
  "pours",
  "bar",
  "chat",
  "learn",
  "scan",
  "search",
  "history",
  "import",
  "signin",
  "signup",
  "login",
  "logout",
  "root",
  "moderator",
  "official",
  "staff",
  "team",
  "system",
  "security",
  "privacy",
  "terms",
  "legal",
  "billing",
  "pro",
  "clubs",
  "club",
  "flights",
  "flight",
  "profile",
  "profiles",
  "feed",
  "home",
  "null",
  "undefined",
  "anonymous",
  "user",
  "users",
  "everyone",
  "whiskeyschool",
];

// Major distillery/brand names — obvious impersonation targets, not an
// exhaustive catalog (see docs/SOCIAL.md D7).
const BRAND_TERMS = [
  "macallan",
  "lagavulin",
  "ardbeg",
  "laphroaig",
  "glenfiddich",
  "glenlivet",
  "buffalotrace",
  "blantons",
  "pappy",
  "pappyvanwinkle",
  "weller",
  "eaglerare",
  "makersmark",
  "jimbeam",
  "jackdaniels",
  "wildturkey",
  "fourroses",
  "knobcreek",
  "bulleit",
  "woodfordreserve",
  "elijahcraig",
  "heavenhill",
  "michters",
  "highwest",
  "redbreast",
  "jameson",
  "bushmills",
  "yamazaki",
  "hibiki",
  "nikka",
  "hakushu",
  "glenmorangie",
  "oban",
  "talisker",
  "springbank",
  "bruichladdich",
  "bowmore",
  "balvenie",
  "glendronach",
  "aberlour",
  "dalmore",
  "chivas",
  "chivasregal",
  "johnniewalker",
  "crownroyal",
];

/** Normalized, reserved handles: app terminology plus major whiskey brands. */
export const RESERVED_HANDLES: ReadonlySet<string> = new Set([...APP_TERMS, ...BRAND_TERMS]);
