/**
 * Whaikey seed catalog: well-known distilleries and bottles, authored as
 * static data with stable slug ids so re-seeding is deterministic.
 *
 * flavorProfile maps every flavor-wheel wedge id (src/lib/flavor-wheel.ts)
 * to a 0-10 intensity. msrp/avgPrice are approximate 2025 US street prices.
 */
import type { WhiskeyCategory } from "../schema";

type WedgeId = "fruity" | "floral" | "grain" | "sweet" | "woody" | "spicy" | "peaty" | "feinty";

export interface SeedDistillery {
  id: string;
  name: string;
  country: string;
  region?: string;
  founded?: number;
  description?: string;
}

export interface SeedBottle {
  id: string;
  distilleryId: string;
  name: string;
  category: WhiskeyCategory;
  region?: string;
  /** null = no age statement (NAS) */
  ageYears: number | null;
  abv: number;
  caskTypes: string[];
  mashBill?: string;
  msrp: number;
  avgPrice: number;
  description: string;
  flavorProfile: Record<WedgeId, number>;
  aliases?: string[];
}

/** Fill unmentioned wedges with 0 so every profile covers all 8 wedges. */
const fp = (p: Partial<Record<WedgeId, number>>): Record<WedgeId, number> => ({
  fruity: 0,
  floral: 0,
  grain: 0,
  sweet: 0,
  woody: 0,
  spicy: 0,
  peaty: 0,
  feinty: 0,
  ...p,
});

export const SEED_DISTILLERIES: SeedDistillery[] = [
  // --- United States: bourbon & rye ---
  { id: "buffalo-trace", name: "Buffalo Trace Distillery", country: "USA", region: "Kentucky", founded: 1858, description: "Frankfort powerhouse behind Buffalo Trace, Eagle Rare, Weller, Blanton's, and the Antique Collection." },
  { id: "heaven-hill", name: "Heaven Hill Distillery", country: "USA", region: "Kentucky", founded: 1935, description: "Family-owned Bardstown giant: Elijah Craig, Larceny, Evan Williams, Rittenhouse." },
  { id: "jim-beam", name: "James B. Beam Distilling Co.", country: "USA", region: "Kentucky", founded: 1795, description: "The world's best-selling bourbon house; also Knob Creek, Booker's, and Old Grand-Dad." },
  { id: "makers-mark", name: "Maker's Mark Distillery", country: "USA", region: "Kentucky", founded: 1953, description: "Loretto wheated-bourbon specialist with the iconic red wax seal." },
  { id: "wild-turkey", name: "Wild Turkey Distillery", country: "USA", region: "Kentucky", founded: 1869, description: "Lawrenceburg distillery famous for high-proof, low-entry-proof bourbons under the Russell family." },
  { id: "four-roses", name: "Four Roses Distillery", country: "USA", region: "Kentucky", founded: 1888, description: "Runs two mash bills and five yeasts for ten distinct bourbon recipes." },
  { id: "woodford-reserve", name: "Woodford Reserve Distillery", country: "USA", region: "Kentucky", founded: 1812, description: "Historic Versailles site using triple copper pot stills alongside column distillate." },
  { id: "old-forester", name: "Old Forester Distilling Co.", country: "USA", region: "Kentucky", founded: 1870, description: "Brown-Forman's founding brand, the first bourbon sold exclusively in sealed bottles." },
  { id: "jack-daniels", name: "Jack Daniel Distillery", country: "USA", region: "Tennessee", founded: 1866, description: "Lynchburg home of charcoal-mellowed Tennessee whiskey." },
  { id: "george-dickel", name: "George Dickel (Cascade Hollow)", country: "USA", region: "Tennessee", founded: 1870, description: "Tullahoma Tennessee whisky distillery known for chill-charcoal mellowing and value bottled-in-bond releases." },
  { id: "barton-1792", name: "Barton 1792 Distillery", country: "USA", region: "Kentucky", founded: 1879, description: "Bardstown distillery (Sazerac) producing the 1792 line." },
  { id: "willett", name: "Willett Distillery", country: "USA", region: "Kentucky", founded: 1936, description: "Family-run Bardstown operation behind Willett, Noah's Mill, and Rowan's Creek." },
  { id: "michters", name: "Michter's Distillery", country: "USA", region: "Kentucky", founded: 1753, description: "Louisville producer tracing heritage to Pennsylvania's Shenk's; US*1 range of bourbon, rye, and sour mash." },
  { id: "bulleit", name: "Bulleit Distilling Co.", country: "USA", region: "Kentucky", founded: 1987, description: "High-rye frontier-style bourbon and 95/5 rye under Diageo." },
  { id: "angels-envy", name: "Angel's Envy Distillery", country: "USA", region: "Kentucky", founded: 2010, description: "Louisville distillery founded by Lincoln Henderson, known for port-finished bourbon." },
  { id: "high-west", name: "High West Distillery", country: "USA", region: "Utah", founded: 2006, description: "Park City blender-distiller celebrated for its rye blends." },
  { id: "whistlepig", name: "WhistlePig Farm", country: "USA", region: "Vermont", founded: 2007, description: "Vermont farm distillery that made aged Canadian-sourced rye a category benchmark." },
  { id: "new-riff", name: "New Riff Distilling", country: "USA", region: "Kentucky", founded: 2014, description: "Newport craft distillery bottling everything bottled-in-bond without chill filtration." },
  // --- United States: single malt & craft ---
  { id: "westland", name: "Westland Distillery", country: "USA", region: "Washington", founded: 2010, description: "Seattle pioneer of American single malt with brewer's-yeast, five-malt whiskeys." },
  { id: "stranahans", name: "Stranahan's Colorado Whiskey", country: "USA", region: "Colorado", founded: 2004, description: "Denver's Rocky Mountain single malt distillery." },
  { id: "balcones", name: "Balcones Distilling", country: "USA", region: "Texas", founded: 2008, description: "Waco distillery known for blue-corn whiskey and boldly aged Texas single malt." },
  { id: "westward", name: "Westward Whiskey", country: "USA", region: "Oregon", founded: 2004, description: "Portland single malt distillery with an ale-yeast, brewing-driven house style." },
  // --- Scotland: single malt ---
  { id: "glenfiddich", name: "Glenfiddich", country: "Scotland", region: "Speyside", founded: 1886, description: "The world's best-selling single malt, still family-owned by William Grant & Sons." },
  { id: "glenlivet", name: "The Glenlivet", country: "Scotland", region: "Speyside", founded: 1824, description: "The first licensed distillery in the glen; the archetypal smooth, floral Speysider." },
  { id: "macallan", name: "The Macallan", country: "Scotland", region: "Speyside", founded: 1824, description: "Famed for sherry-seasoned oak and luxury positioning." },
  { id: "balvenie", name: "The Balvenie", country: "Scotland", region: "Speyside", founded: 1892, description: "Dufftown distillery with its own floor maltings; honeyed house style." },
  { id: "glenfarclas", name: "Glenfarclas", country: "Scotland", region: "Speyside", founded: 1836, description: "Grant family-owned, direct-fired stills, sherry-cask tradition at fair prices." },
  { id: "aberlour", name: "Aberlour", country: "Scotland", region: "Speyside", founded: 1879, description: "Speyside distillery famous for the cask-strength, sherried A'bunadh." },
  { id: "glenmorangie", name: "Glenmorangie", country: "Scotland", region: "Highland", founded: 1843, description: "Tain distillery with Scotland's tallest stills and a delicate, citrusy spirit." },
  { id: "glendronach", name: "The GlenDronach", country: "Scotland", region: "Highland", founded: 1826, description: "Heavily sherried Highland malt matured in PX and oloroso casks." },
  { id: "dalmore", name: "The Dalmore", country: "Scotland", region: "Highland", founded: 1839, description: "Northern Highland distillery known for rich, orange-and-chocolate sherried malts." },
  { id: "oban", name: "Oban", country: "Scotland", region: "Highland", founded: 1794, description: "Tiny west-coast distillery bridging Highland fruit and maritime salt." },
  { id: "highland-park", name: "Highland Park", country: "Scotland", region: "Islands", founded: 1798, description: "Orkney distillery balancing heather honey with gentle floor-malted peat smoke." },
  { id: "talisker", name: "Talisker", country: "Scotland", region: "Islands", founded: 1830, description: "Isle of Skye's oldest distillery; peppery, maritime single malt." },
  { id: "springbank", name: "Springbank", country: "Scotland", region: "Campbeltown", founded: 1828, description: "Campbeltown's family-owned distillery doing 100% of production on site; also makes Longrow and Hazelburn." },
  { id: "auchentoshan", name: "Auchentoshan", country: "Scotland", region: "Lowland", founded: 1823, description: "Triple-distilled Lowland malt just outside Glasgow." },
  { id: "lagavulin", name: "Lagavulin", country: "Scotland", region: "Islay", founded: 1816, description: "Islay icon producing rich, smoky, slow-distilled malts." },
  { id: "laphroaig", name: "Laphroaig", country: "Scotland", region: "Islay", founded: 1815, description: "Medicinal, iodine-rich Islay malt with its own floor maltings." },
  { id: "ardbeg", name: "Ardbeg", country: "Scotland", region: "Islay", founded: 1815, description: "Kildalton distillery making intensely peaty yet citrus-bright whisky." },
  { id: "bowmore", name: "Bowmore", country: "Scotland", region: "Islay", founded: 1779, description: "Islay's oldest distillery; balanced mid-weight peat and tropical fruit." },
  { id: "bruichladdich", name: "Bruichladdich", country: "Scotland", region: "Islay", founded: 1881, description: "Progressive Islay distillery: unpeated Laddie, heavily peated Port Charlotte and Octomore." },
  { id: "bunnahabhain", name: "Bunnahabhain", country: "Scotland", region: "Islay", founded: 1881, description: "The gentle Islay: mostly unpeated, sherried, coastal." },
  { id: "caol-ila", name: "Caol Ila", country: "Scotland", region: "Islay", founded: 1846, description: "Islay's largest distillery; lighter, grassy-smoky malt and a Johnnie Walker workhorse." },
  { id: "kilchoman", name: "Kilchoman", country: "Scotland", region: "Islay", founded: 2005, description: "Islay farm distillery growing barley on site for citrusy, peaty malts." },
  // --- Scotland: blending houses ---
  { id: "johnnie-walker", name: "Johnnie Walker (Diageo)", country: "Scotland", founded: 1820, description: "The world's best-selling Scotch whisky blend house." },
  { id: "chivas-brothers", name: "Chivas Brothers", country: "Scotland", founded: 1801, description: "Pernod Ricard's Scotch house: Chivas Regal and Ballantine's." },
  { id: "dewars", name: "John Dewar & Sons", country: "Scotland", founded: 1846, description: "Aberfeldy-anchored blending house known for double-aged blends." },
  { id: "compass-box", name: "Compass Box", country: "Scotland", founded: 2000, description: "Modern boutique Scotch blender with transparent recipes." },
  { id: "william-grant-sons", name: "William Grant & Sons", country: "Scotland", founded: 1887, description: "Independent family firm behind Glenfiddich, Balvenie, and Monkey Shoulder." },
  // --- Ireland ---
  { id: "midleton", name: "Midleton Distillery", country: "Ireland", region: "Cork", founded: 1825, description: "Irish Distillers' Cork campus: Jameson, Redbreast, the Spots, Powers, Midleton Very Rare." },
  { id: "bushmills", name: "Old Bushmills Distillery", country: "Ireland", region: "County Antrim", founded: 1608, description: "The world's oldest licensed distillery; triple-distilled single malts." },
  { id: "teeling", name: "Teeling Whiskey Distillery", country: "Ireland", region: "Dublin", founded: 2015, description: "The distillery that brought whiskey-making back to Dublin." },
  { id: "tullamore", name: "Tullamore Distillery", country: "Ireland", region: "County Offaly", founded: 1829, description: "Home of Tullamore D.E.W. triple-blend Irish whiskey." },
  { id: "kilbeggan", name: "Kilbeggan / Cooley Distillery", country: "Ireland", region: "County Westmeath", founded: 1757, description: "Historic distillery revived by Cooley; makes Tyrconnell and peated Connemara." },
  // --- Japan ---
  { id: "suntory", name: "Suntory (Yamazaki & Hakushu)", country: "Japan", founded: 1923, description: "Japan's first whisky house: Yamazaki, Hakushu, Hibiki, Toki." },
  { id: "nikka", name: "Nikka Whisky (Yoichi & Miyagikyo)", country: "Japan", founded: 1934, description: "Masataka Taketsuru's company, running the Yoichi and Miyagikyo distilleries." },
  { id: "chichibu", name: "Chichibu Distillery", country: "Japan", region: "Saitama", founded: 2008, description: "Ichiro Akuto's cult craft distillery north of Tokyo." },
  // --- Canada ---
  { id: "crown-royal", name: "Crown Royal (Gimli)", country: "Canada", region: "Manitoba", founded: 1939, description: "Canada's best-selling whisky, distilled at Gimli on Lake Winnipeg." },
  { id: "hiram-walker", name: "Hiram Walker & Sons", country: "Canada", region: "Ontario", founded: 1858, description: "Windsor distillery producing J.P. Wiser's, Lot No. 40, Pike Creek, and Canadian Club." },
  { id: "alberta-distillers", name: "Alberta Distillers", country: "Canada", region: "Alberta", founded: 1946, description: "Calgary distillery famous for 100% rye whisky." },
  // --- World ---
  { id: "kavalan", name: "Kavalan Distillery", country: "Taiwan", region: "Yilan", founded: 2005, description: "Sub-tropical maturation yields lush, fast-aged Taiwanese single malt." },
  { id: "amrut", name: "Amrut Distilleries", country: "India", region: "Bangalore", founded: 1948, description: "Indian single malt pioneer; tropical aging concentrates flavor fast." },
  { id: "penderyn", name: "Penderyn Distillery", country: "Wales", region: "Brecon Beacons", founded: 2000, description: "Welsh single malt distilled on a unique Faraday still." },
  { id: "starward", name: "Starward Whisky", country: "Australia", region: "Melbourne", founded: 2007, description: "Australian whisky matured in local red-wine barrels." },
];

export const SEED_BOTTLES: SeedBottle[] = [
  // =========================================================================
  // BOURBON
  // =========================================================================
  { id: "buffalo-trace", distilleryId: "buffalo-trace", name: "Buffalo Trace", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 45, caskTypes: ["new charred oak"], mashBill: "BT mash bill #1 (low rye, undisclosed)", msrp: 30, avgPrice: 35,
    description: "The flagship Frankfort bourbon: brown sugar, vanilla, and gentle oak at an everyday price.",
    flavorProfile: fp({ sweet: 7, woody: 5, fruity: 3, spicy: 3, grain: 3, floral: 1 }), aliases: ["BT"] },
  { id: "eagle-rare-10", distilleryId: "buffalo-trace", name: "Eagle Rare 10 Year", category: "bourbon", region: "Kentucky",
    ageYears: 10, abv: 45, caskTypes: ["new charred oak"], mashBill: "BT mash bill #1 (low rye, undisclosed)", msrp: 40, avgPrice: 55,
    description: "Ten-year Buffalo Trace with more oak, toffee, and cherry depth; a shelf unicorn at MSRP.",
    flavorProfile: fp({ sweet: 7, woody: 7, fruity: 4, spicy: 3, grain: 2, feinty: 1 }), aliases: ["ER10", "Eagle Rare"] },
  { id: "blantons-original", distilleryId: "buffalo-trace", name: "Blanton's Original Single Barrel", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 46.5, caskTypes: ["new charred oak"], mashBill: "BT mash bill #2 (higher rye, undisclosed)", msrp: 75, avgPrice: 110,
    description: "The original single barrel bourbon, sold in the horse-topped grenade bottle; caramel, citrus, and baking spice.",
    flavorProfile: fp({ sweet: 7, woody: 5, spicy: 5, fruity: 5, grain: 2, floral: 1 }), aliases: ["Blanton's", "Blantons SB"] },
  { id: "weller-special-reserve", distilleryId: "buffalo-trace", name: "W.L. Weller Special Reserve", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 45, caskTypes: ["new charred oak"], mashBill: "Wheated (wheat replaces rye)", msrp: 30, avgPrice: 55,
    description: "Entry wheated bourbon from the Weller line; soft, sweet, and honeyed.",
    flavorProfile: fp({ sweet: 8, woody: 4, fruity: 3, grain: 3, spicy: 2, floral: 1 }), aliases: ["Weller SR", "WSR"] },
  { id: "weller-antique-107", distilleryId: "buffalo-trace", name: "W.L. Weller Antique 107", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 53.5, caskTypes: ["new charred oak"], mashBill: "Wheated (wheat replaces rye)", msrp: 55, avgPrice: 110,
    description: "The 107-proof Weller: cherry cola, cinnamon red hots, and caramel with real punch.",
    flavorProfile: fp({ sweet: 8, spicy: 5, woody: 5, fruity: 5, grain: 2, feinty: 1 }), aliases: ["OWA", "Weller Antique", "Old Weller Antique"] },
  { id: "weller-12", distilleryId: "buffalo-trace", name: "W.L. Weller 12 Year", category: "bourbon", region: "Kentucky",
    ageYears: 12, abv: 45, caskTypes: ["new charred oak"], mashBill: "Wheated (wheat replaces rye)", msrp: 60, avgPrice: 220,
    description: "Long-aged wheater often called 'poor man's Pappy'; plush toffee, leather, and dark fruit.",
    flavorProfile: fp({ sweet: 8, woody: 7, fruity: 5, spicy: 2, grain: 1, feinty: 2 }), aliases: ["W12", "Weller 12"] },
  { id: "eh-taylor-small-batch", distilleryId: "buffalo-trace", name: "E.H. Taylor, Jr. Small Batch", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 50, caskTypes: ["new charred oak"], mashBill: "BT mash bill #1 (low rye, undisclosed)", msrp: 47, avgPrice: 90,
    description: "Bottled-in-bond tribute to Colonel Taylor; butterscotch, corn sweetness, and tobacco.",
    flavorProfile: fp({ sweet: 7, woody: 6, spicy: 4, fruity: 3, grain: 3, feinty: 1 }), aliases: ["EHT", "EHT Small Batch", "EHTSB"] },
  { id: "stagg", distilleryId: "buffalo-trace", name: "Stagg", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 64.5, caskTypes: ["new charred oak"], mashBill: "BT mash bill #1 (low rye, undisclosed)", msrp: 70, avgPrice: 130,
    description: "Uncut, unfiltered barrel-proof bruiser (formerly Stagg Jr.); dark cherry, molasses, and heavy char.",
    flavorProfile: fp({ sweet: 8, woody: 8, spicy: 6, fruity: 5, grain: 1, feinty: 2 }), aliases: ["Stagg Jr", "Stagg Junior"] },
  { id: "george-t-stagg", distilleryId: "buffalo-trace", name: "George T. Stagg", category: "bourbon", region: "Kentucky",
    ageYears: 15, abv: 69, caskTypes: ["new charred oak"], mashBill: "BT mash bill #1 (low rye, undisclosed)", msrp: 125, avgPrice: 1300,
    description: "The Antique Collection's hazmat-proof legend: fifteen years of oak, fudge, and espresso.",
    flavorProfile: fp({ woody: 9, sweet: 8, spicy: 6, fruity: 5, feinty: 2, grain: 1 }), aliases: ["GTS", "BTAC Stagg"] },
  { id: "william-larue-weller", distilleryId: "buffalo-trace", name: "William Larue Weller", category: "bourbon", region: "Kentucky",
    ageYears: 12, abv: 62.6, caskTypes: ["new charred oak"], mashBill: "Wheated (wheat replaces rye)", msrp: 125, avgPrice: 1300,
    description: "Barrel-proof wheated centerpiece of the Antique Collection; caramel-soaked dark fruit and velvet oak.",
    flavorProfile: fp({ sweet: 9, woody: 7, fruity: 6, spicy: 3, feinty: 2, grain: 1 }), aliases: ["WLW", "BTAC Weller"] },
  { id: "elijah-craig-small-batch", distilleryId: "heaven-hill", name: "Elijah Craig Small Batch", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 47, caskTypes: ["new charred oak"], mashBill: "78% corn, 10% rye, 12% malted barley", msrp: 30, avgPrice: 33,
    description: "Benchmark value bourbon with honey, toasted oak, and nutmeg.",
    flavorProfile: fp({ sweet: 7, woody: 6, spicy: 4, fruity: 3, grain: 3 }), aliases: ["EC", "ECSB"] },
  { id: "elijah-craig-barrel-proof", distilleryId: "heaven-hill", name: "Elijah Craig Barrel Proof", category: "bourbon", region: "Kentucky",
    ageYears: 12, abv: 61.5, caskTypes: ["new charred oak"], mashBill: "78% corn, 10% rye, 12% malted barley", msrp: 70, avgPrice: 90,
    description: "Thrice-yearly barrel-proof batches of well-aged Elijah Craig; blackened oak, dark chocolate, and cinnamon.",
    flavorProfile: fp({ woody: 8, sweet: 8, spicy: 6, fruity: 4, grain: 2, feinty: 2 }), aliases: ["ECBP"] },
  { id: "henry-mckenna-10", distilleryId: "heaven-hill", name: "Henry McKenna Single Barrel 10 Year Bottled-in-Bond", category: "bourbon", region: "Kentucky",
    ageYears: 10, abv: 50, caskTypes: ["new charred oak"], mashBill: "78% corn, 10% rye, 12% malted barley", msrp: 40, avgPrice: 60,
    description: "Ten-year bonded single barrel that won SF World Spirits' best whiskey in 2019.",
    flavorProfile: fp({ sweet: 7, woody: 7, spicy: 5, fruity: 3, grain: 2, feinty: 1 }), aliases: ["McKenna 10", "HMcK"] },
  { id: "larceny-small-batch", distilleryId: "heaven-hill", name: "Larceny Small Batch", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 46, caskTypes: ["new charred oak"], mashBill: "68% corn, 20% wheat, 12% malted barley", msrp: 27, avgPrice: 28,
    description: "Heaven Hill's wheated everyday pour; soft caramel and fresh bread.",
    flavorProfile: fp({ sweet: 7, grain: 4, woody: 4, fruity: 3, spicy: 2 }), aliases: ["Larceny"] },
  { id: "larceny-barrel-proof", distilleryId: "heaven-hill", name: "Larceny Barrel Proof", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 61, caskTypes: ["new charred oak"], mashBill: "68% corn, 20% wheat, 12% malted barley", msrp: 55, avgPrice: 65,
    description: "Full-proof wheated batches with maple syrup, stewed fruit, and toasted oak.",
    flavorProfile: fp({ sweet: 9, woody: 6, fruity: 5, spicy: 4, grain: 2, feinty: 1 }), aliases: ["LBP"] },
  { id: "evan-williams-black", distilleryId: "heaven-hill", name: "Evan Williams Black Label", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 43, caskTypes: ["new charred oak"], mashBill: "78% corn, 10% rye, 12% malted barley", msrp: 16, avgPrice: 16,
    description: "One of the best sub-$20 bourbons: light caramel, corn, and vanilla.",
    flavorProfile: fp({ sweet: 6, grain: 4, woody: 4, fruity: 2, spicy: 2 }), aliases: ["EW Black", "Evan Williams"] },
  { id: "evan-williams-bib", distilleryId: "heaven-hill", name: "Evan Williams Bottled-in-Bond", category: "bourbon", region: "Kentucky",
    ageYears: 4, abv: 50, caskTypes: ["new charred oak"], mashBill: "78% corn, 10% rye, 12% malted barley", msrp: 20, avgPrice: 20,
    description: "The white-label bonded budget champion; bigger oak and spice than the Black Label.",
    flavorProfile: fp({ sweet: 6, woody: 5, spicy: 4, grain: 4, fruity: 2 }), aliases: ["EW BiB", "EWBIB"] },
  { id: "heaven-hill-bib-7", distilleryId: "heaven-hill", name: "Heaven Hill Bottled-in-Bond 7 Year", category: "bourbon", region: "Kentucky",
    ageYears: 7, abv: 50, caskTypes: ["new charred oak"], mashBill: "78% corn, 10% rye, 12% malted barley", msrp: 50, avgPrice: 55,
    description: "The namesake bonded seven-year; classic Heaven Hill nuttiness, char, and caramel corn.",
    flavorProfile: fp({ sweet: 6, woody: 6, grain: 4, spicy: 4, fruity: 2, feinty: 1 }), aliases: ["HH BiB", "HH7"] },
  { id: "jim-beam-white", distilleryId: "jim-beam", name: "Jim Beam White Label", category: "bourbon", region: "Kentucky",
    ageYears: 4, abv: 40, caskTypes: ["new charred oak"], mashBill: "77% corn, 13% rye, 10% malted barley", msrp: 18, avgPrice: 18,
    description: "The world's best-selling bourbon; light, peanutty, and easygoing.",
    flavorProfile: fp({ grain: 5, sweet: 5, woody: 3, fruity: 2, spicy: 2, feinty: 2 }), aliases: ["Beam White"] },
  { id: "knob-creek-9", distilleryId: "jim-beam", name: "Knob Creek 9 Year", category: "bourbon", region: "Kentucky",
    ageYears: 9, abv: 50, caskTypes: ["new charred oak"], mashBill: "77% corn, 13% rye, 10% malted barley", msrp: 37, avgPrice: 38,
    description: "Beam's pre-Prohibition style small batch: heavy char, roasted nuts, and brown sugar.",
    flavorProfile: fp({ woody: 7, sweet: 7, spicy: 4, grain: 3, fruity: 2, feinty: 1 }), aliases: ["KC9", "Knob Creek"] },
  { id: "knob-creek-12", distilleryId: "jim-beam", name: "Knob Creek 12 Year", category: "bourbon", region: "Kentucky",
    ageYears: 12, abv: 50, caskTypes: ["new charred oak"], mashBill: "77% corn, 13% rye, 10% malted barley", msrp: 65, avgPrice: 70,
    description: "Extra-aged Knob Creek layering espresso and dark chocolate over the house peanut-brittle core.",
    flavorProfile: fp({ woody: 8, sweet: 7, spicy: 4, fruity: 3, grain: 2, feinty: 1 }), aliases: ["KC12"] },
  { id: "bookers", distilleryId: "jim-beam", name: "Booker's Bourbon", category: "bourbon", region: "Kentucky",
    ageYears: 6, abv: 63, caskTypes: ["new charred oak"], mashBill: "77% corn, 13% rye, 10% malted barley", msrp: 90, avgPrice: 100,
    description: "Uncut, unfiltered small batch released in named batches; intense vanilla, peanut, and oak heat.",
    flavorProfile: fp({ sweet: 8, woody: 7, spicy: 6, grain: 3, fruity: 3, feinty: 2 }), aliases: ["Bookers"] },
  { id: "basil-hayden", distilleryId: "jim-beam", name: "Basil Hayden", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 40, caskTypes: ["new charred oak"], mashBill: "63% corn, 27% rye, 10% malted barley", msrp: 45, avgPrice: 45,
    description: "Gentle high-rye sipper: tea, pepper, and honey at approachable proof.",
    flavorProfile: fp({ spicy: 5, sweet: 5, fruity: 3, grain: 3, woody: 3, floral: 2 }), aliases: ["Basil Hayden's"] },
  { id: "old-grand-dad-114", distilleryId: "jim-beam", name: "Old Grand-Dad 114", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 57, caskTypes: ["new charred oak"], mashBill: "63% corn, 27% rye, 10% malted barley", msrp: 35, avgPrice: 40,
    description: "High-rye, high-proof cult value bourbon; cinnamon, orange peel, and caramel corn.",
    flavorProfile: fp({ spicy: 7, sweet: 7, woody: 5, fruity: 4, grain: 3, feinty: 1 }), aliases: ["OGD 114", "OGD114"] },
  { id: "makers-mark", distilleryId: "makers-mark", name: "Maker's Mark", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 45, caskTypes: ["new charred oak"], mashBill: "70% corn, 16% red winter wheat, 14% malted barley", msrp: 30, avgPrice: 30,
    description: "The red-wax wheated standard: soft caramel, baked bread, and vanilla.",
    flavorProfile: fp({ sweet: 7, grain: 4, woody: 4, fruity: 3, spicy: 2, floral: 1 }), aliases: ["MM", "Makers"] },
  { id: "makers-mark-46", distilleryId: "makers-mark", name: "Maker's Mark 46", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 47, caskTypes: ["new charred oak", "seared French oak staves"], mashBill: "70% corn, 16% red winter wheat, 14% malted barley", msrp: 40, avgPrice: 42,
    description: "Maker's finished on seared French oak staves for extra baking spice and toasted sugar.",
    flavorProfile: fp({ sweet: 8, woody: 6, spicy: 4, fruity: 3, grain: 3 }), aliases: ["MM46", "Makers 46"] },
  { id: "makers-mark-cask-strength", distilleryId: "makers-mark", name: "Maker's Mark Cask Strength", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 55, caskTypes: ["new charred oak"], mashBill: "70% corn, 16% red winter wheat, 14% malted barley", msrp: 45, avgPrice: 60,
    description: "Barrel-proof Maker's that keeps the soft wheated core while amplifying caramel and oak.",
    flavorProfile: fp({ sweet: 8, woody: 6, spicy: 4, fruity: 4, grain: 2 }), aliases: ["MMCS", "Makers CS"] },
  { id: "wild-turkey-101", distilleryId: "wild-turkey", name: "Wild Turkey 101", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 50.5, caskTypes: ["new charred oak"], mashBill: "75% corn, 13% rye, 12% malted barley", msrp: 27, avgPrice: 28,
    description: "The enthusiast's house pour: bold vanilla, toffee, and rye spice at 101 proof.",
    flavorProfile: fp({ sweet: 7, spicy: 6, woody: 6, fruity: 3, grain: 3, feinty: 1 }), aliases: ["WT101", "Turkey 101"] },
  { id: "wild-turkey-rare-breed", distilleryId: "wild-turkey", name: "Wild Turkey Rare Breed", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 58.4, caskTypes: ["new charred oak"], mashBill: "75% corn, 13% rye, 12% malted barley", msrp: 55, avgPrice: 55,
    description: "Barrel-proof blend of 6-12 year Turkey stocks; orange, leather, clove, and deep toffee.",
    flavorProfile: fp({ spicy: 7, sweet: 7, woody: 7, fruity: 4, grain: 2, feinty: 2 }), aliases: ["WTRB", "Rare Breed"] },
  { id: "russells-reserve-10", distilleryId: "wild-turkey", name: "Russell's Reserve 10 Year", category: "bourbon", region: "Kentucky",
    ageYears: 10, abv: 45, caskTypes: ["new charred oak"], mashBill: "75% corn, 13% rye, 12% malted barley", msrp: 40, avgPrice: 45,
    description: "The Russells' ten-year small batch: creamy vanilla, oak, and orange zest.",
    flavorProfile: fp({ sweet: 7, woody: 6, spicy: 5, fruity: 4, grain: 2, feinty: 1 }), aliases: ["RR10"] },
  { id: "russells-reserve-13", distilleryId: "wild-turkey", name: "Russell's Reserve 13 Year", category: "bourbon", region: "Kentucky",
    ageYears: 13, abv: 58, caskTypes: ["new charred oak"], mashBill: "75% corn, 13% rye, 12% malted barley", msrp: 100, avgPrice: 200,
    description: "Barrel-proof teenage Turkey that became an instant modern classic; caramel-drenched oak and cherry.",
    flavorProfile: fp({ woody: 8, sweet: 8, fruity: 5, spicy: 6, feinty: 2 }), aliases: ["RR13"] },
  { id: "russells-reserve-single-barrel", distilleryId: "wild-turkey", name: "Russell's Reserve Single Barrel", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 55, caskTypes: ["new charred oak"], mashBill: "75% corn, 13% rye, 12% malted barley", msrp: 65, avgPrice: 65,
    description: "Non-chill-filtered 110-proof single barrels; the sweet spot of the Turkey lineup.",
    flavorProfile: fp({ sweet: 7, woody: 7, spicy: 6, fruity: 4, grain: 2, feinty: 1 }), aliases: ["RRSiB", "RRSB"] },
  { id: "four-roses-bourbon", distilleryId: "four-roses", name: "Four Roses Bourbon", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 40, caskTypes: ["new charred oak"], mashBill: "Blend of 60% and 75% corn high-rye mash bills", msrp: 22, avgPrice: 22,
    description: "The Yellow Label: light, floral, and fruity — a gentle high-rye intro.",
    flavorProfile: fp({ fruity: 4, floral: 4, sweet: 5, spicy: 3, grain: 3, woody: 3 }), aliases: ["Four Roses Yellow"] },
  { id: "four-roses-small-batch", distilleryId: "four-roses", name: "Four Roses Small Batch", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 45, caskTypes: ["new charred oak"], mashBill: "Four recipes from two high-rye mash bills", msrp: 35, avgPrice: 35,
    description: "Four-recipe marriage with red berries, caramel, and mellow spice.",
    flavorProfile: fp({ fruity: 5, sweet: 6, spicy: 4, floral: 3, woody: 4, grain: 2 }), aliases: ["FRSmB"] },
  { id: "four-roses-single-barrel", distilleryId: "four-roses", name: "Four Roses Single Barrel", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 50, caskTypes: ["new charred oak"], mashBill: "OBSV: 60% corn, 35% rye, 5% malted barley", msrp: 50, avgPrice: 50,
    description: "The OBSV recipe at 100 proof: ripe plum, pear, cinnamon, and cocoa.",
    flavorProfile: fp({ fruity: 6, spicy: 6, sweet: 6, woody: 5, floral: 3, grain: 1 }), aliases: ["FRSB", "Four Roses SB", "Four Roses SiB"] },
  { id: "four-roses-small-batch-select", distilleryId: "four-roses", name: "Four Roses Small Batch Select", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 52, caskTypes: ["new charred oak"], mashBill: "Six recipes, non-chill filtered", msrp: 60, avgPrice: 65,
    description: "Six-recipe, non-chill-filtered step up; raspberry, clove, and creamy oak.",
    flavorProfile: fp({ fruity: 6, spicy: 6, sweet: 6, woody: 5, floral: 3, grain: 1 }), aliases: ["FRSBS", "Small Batch Select"] },
  { id: "woodford-reserve", distilleryId: "woodford-reserve", name: "Woodford Reserve Distiller's Select", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 45.2, caskTypes: ["new charred oak"], mashBill: "72% corn, 18% rye, 10% malted barley", msrp: 40, avgPrice: 38,
    description: "Pot-still-influenced flagship with dried fruit, cocoa, and toasty oak.",
    flavorProfile: fp({ sweet: 6, woody: 6, fruity: 4, spicy: 4, grain: 3, feinty: 1 }), aliases: ["Woodford"] },
  { id: "woodford-double-oaked", distilleryId: "woodford-reserve", name: "Woodford Reserve Double Oaked", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 45.2, caskTypes: ["new charred oak", "second deeply toasted oak"], mashBill: "72% corn, 18% rye, 10% malted barley", msrp: 60, avgPrice: 60,
    description: "Finished in a second heavily toasted barrel; dessert-like caramel, hazelnut, and dark chocolate.",
    flavorProfile: fp({ sweet: 9, woody: 8, fruity: 3, spicy: 3, grain: 1 }), aliases: ["WDO", "Double Oaked"] },
  { id: "old-forester-86", distilleryId: "old-forester", name: "Old Forester 86 Proof", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 43, caskTypes: ["new charred oak"], mashBill: "72% corn, 18% rye, 10% malted barley", msrp: 25, avgPrice: 25,
    description: "America's first bottled bourbon; banana, caramel, and light spice.",
    flavorProfile: fp({ sweet: 6, fruity: 4, spicy: 4, woody: 4, grain: 3 }), aliases: ["OF 86"] },
  { id: "old-forester-1910", distilleryId: "old-forester", name: "Old Forester 1910 Old Fine Whisky", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 46.5, caskTypes: ["new charred oak", "second heavily charred oak"], mashBill: "72% corn, 18% rye, 10% malted barley", msrp: 65, avgPrice: 60,
    description: "Double-barreled in heavily charred oak; a caramel-and-marshmallow dessert pour.",
    flavorProfile: fp({ sweet: 9, woody: 7, spicy: 3, fruity: 3, grain: 1 }), aliases: ["OF 1910", "1910"] },
  { id: "old-forester-1920", distilleryId: "old-forester", name: "Old Forester 1920 Prohibition Style", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 57.5, caskTypes: ["new charred oak"], mashBill: "72% corn, 18% rye, 10% malted barley", msrp: 65, avgPrice: 65,
    description: "115-proof nod to Prohibition-era barrels; dark caramel, cocoa, cherry, and smoky char.",
    flavorProfile: fp({ sweet: 8, woody: 7, spicy: 6, fruity: 5, grain: 1, feinty: 1 }), aliases: ["OF 1920", "1920"] },
  { id: "1792-small-batch", distilleryId: "barton-1792", name: "1792 Small Batch", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 46.85, caskTypes: ["new charred oak"], mashBill: "High rye (undisclosed)", msrp: 32, avgPrice: 33,
    description: "Barton's flagship high-rye; brown sugar, apple, and peppery spice.",
    flavorProfile: fp({ spicy: 5, sweet: 6, woody: 5, fruity: 4, grain: 2, feinty: 1 }), aliases: ["1792"] },
  { id: "1792-full-proof", distilleryId: "barton-1792", name: "1792 Full Proof", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 62.5, caskTypes: ["new charred oak"], mashBill: "High rye (undisclosed)", msrp: 45, avgPrice: 55,
    description: "Bottled at its 125 entry proof; intense caramel, cherry, and toasted oak.",
    flavorProfile: fp({ sweet: 8, woody: 7, spicy: 6, fruity: 5, grain: 1, feinty: 1 }), aliases: ["1792 FP", "Full Proof"] },
  { id: "willett-pot-still-reserve", distilleryId: "willett", name: "Willett Pot Still Reserve", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 47, caskTypes: ["new charred oak"], mashBill: "High corn (undisclosed)", msrp: 45, avgPrice: 50,
    description: "The pot-still-shaped decanter bourbon; light caramel, citrus, and fresh oak.",
    flavorProfile: fp({ sweet: 6, fruity: 4, woody: 5, spicy: 4, grain: 3 }), aliases: ["WPS", "Willett Pot Still"] },
  { id: "noahs-mill", distilleryId: "willett", name: "Noah's Mill", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 57.15, caskTypes: ["new charred oak"], mashBill: "Blend of Willett mash bills (undisclosed)", msrp: 65, avgPrice: 70,
    description: "Willett's brawny small batch: walnut, dark caramel, and old oak.",
    flavorProfile: fp({ woody: 7, sweet: 7, spicy: 6, fruity: 4, feinty: 2, grain: 1 }), aliases: ["Noahs Mill"] },
  { id: "michters-us1-bourbon", distilleryId: "michters", name: "Michter's US*1 Kentucky Straight Bourbon", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 45.7, caskTypes: ["new charred oak"], mashBill: "High corn (undisclosed)", msrp: 50, avgPrice: 50,
    description: "Polished small batch with butterscotch, stone fruit, and gentle smoke-kissed oak.",
    flavorProfile: fp({ sweet: 7, woody: 5, fruity: 4, spicy: 3, grain: 2, feinty: 1 }), aliases: ["Michters Bourbon", "Michter's Small Batch"] },
  { id: "bulleit-bourbon", distilleryId: "bulleit", name: "Bulleit Bourbon", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 45, caskTypes: ["new charred oak"], mashBill: "68% corn, 28% rye, 4% malted barley", msrp: 28, avgPrice: 28,
    description: "High-rye frontier whiskey; dry, spicy, with maple and light oak.",
    flavorProfile: fp({ spicy: 6, sweet: 5, woody: 4, fruity: 3, grain: 3 }), aliases: ["Bulleit"] },
  { id: "angels-envy-bourbon", distilleryId: "angels-envy", name: "Angel's Envy Kentucky Straight Bourbon", category: "bourbon", region: "Kentucky",
    ageYears: null, abv: 43.3, caskTypes: ["new charred oak", "port"], mashBill: "72% corn, 18% rye, 10% malted barley", msrp: 60, avgPrice: 55,
    description: "Port-cask finish layers raisin and red berry over vanilla and toast.",
    flavorProfile: fp({ fruity: 6, sweet: 7, woody: 4, spicy: 3, grain: 2 }), aliases: ["AE", "Angels Envy"] },
  { id: "new-riff-bib-bourbon", distilleryId: "new-riff", name: "New Riff Bottled-in-Bond Bourbon", category: "bourbon", region: "Kentucky",
    ageYears: 4, abv: 50, caskTypes: ["new charred oak"], mashBill: "65% corn, 30% rye, 5% malted barley", msrp: 45, avgPrice: 45,
    description: "Kentucky-regular craft bonded bourbon, high-rye and non-chill filtered.",
    flavorProfile: fp({ spicy: 6, sweet: 6, woody: 5, fruity: 3, grain: 3 }), aliases: ["New Riff BiB"] },

  // =========================================================================
  // RYE
  // =========================================================================
  { id: "sazerac-rye", distilleryId: "buffalo-trace", name: "Sazerac Rye", category: "rye", region: "Kentucky",
    ageYears: null, abv: 45, caskTypes: ["new charred oak"], mashBill: "Barely-legal rye (~51% rye, undisclosed)", msrp: 30, avgPrice: 40,
    description: "The classic cocktail rye of New Orleans; anise, clove, and candied citrus.",
    flavorProfile: fp({ spicy: 6, sweet: 5, fruity: 4, woody: 4, grain: 3, floral: 2 }), aliases: ["Baby Saz"] },
  { id: "thomas-h-handy", distilleryId: "buffalo-trace", name: "Thomas H. Handy Sazerac Rye", category: "rye", region: "Kentucky",
    ageYears: 6, abv: 64.5, caskTypes: ["new charred oak"], mashBill: "Barely-legal rye (~51% rye, undisclosed)", msrp: 125, avgPrice: 900,
    description: "The Antique Collection's uncut rye; cinnamon fireball, mint, and dark cherry.",
    flavorProfile: fp({ spicy: 8, sweet: 6, fruity: 5, woody: 6, floral: 2, feinty: 1 }), aliases: ["THH", "Handy"] },
  { id: "sazerac-18", distilleryId: "buffalo-trace", name: "Sazerac Rye 18 Year", category: "rye", region: "Kentucky",
    ageYears: 18, abv: 45, caskTypes: ["new charred oak"], mashBill: "Barely-legal rye (~51% rye, undisclosed)", msrp: 125, avgPrice: 1000,
    description: "Long-aged BTAC rye trading fire for polished oak, leather, and dried fruit.",
    flavorProfile: fp({ woody: 8, spicy: 6, sweet: 5, fruity: 5, feinty: 2 }), aliases: ["Saz 18"] },
  { id: "rittenhouse-bib", distilleryId: "heaven-hill", name: "Rittenhouse Rye Bottled-in-Bond", category: "rye", region: "Kentucky",
    ageYears: 4, abv: 50, caskTypes: ["new charred oak"], mashBill: "51% rye, 37% corn, 12% malted barley", msrp: 28, avgPrice: 30,
    description: "The bartender's bonded rye; cocoa, black pepper, and caramel.",
    flavorProfile: fp({ spicy: 6, sweet: 5, woody: 5, grain: 4, fruity: 2 }), aliases: ["Ritt", "Rittenhouse"] },
  { id: "pikesville-6", distilleryId: "heaven-hill", name: "Pikesville 6 Year 110 Proof Rye", category: "rye", region: "Kentucky",
    ageYears: 6, abv: 55, caskTypes: ["new charred oak"], mashBill: "51% rye, 37% corn, 12% malted barley", msrp: 55, avgPrice: 60,
    description: "Rittenhouse's older, stronger sibling reviving a Maryland-style label; cocoa, clove, and toffee.",
    flavorProfile: fp({ spicy: 7, sweet: 6, woody: 6, fruity: 3, grain: 3 }), aliases: ["Pikesville"] },
  { id: "knob-creek-rye", distilleryId: "jim-beam", name: "Knob Creek Rye", category: "rye", region: "Kentucky",
    ageYears: 7, abv: 50, caskTypes: ["new charred oak"], mashBill: "Beam rye (~51% rye)", msrp: 40, avgPrice: 40,
    description: "Full-bodied Beam rye with herbal spice riding on caramel and char.",
    flavorProfile: fp({ spicy: 6, woody: 6, sweet: 5, grain: 3, floral: 2, fruity: 2 }), aliases: ["KC Rye"] },
  { id: "old-overholt-bib", distilleryId: "jim-beam", name: "Old Overholt Bottled-in-Bond Rye", category: "rye", region: "Kentucky",
    ageYears: 4, abv: 50, caskTypes: ["new charred oak"], mashBill: "Beam rye (~51% rye)", msrp: 30, avgPrice: 30,
    description: "America's oldest continuously maintained whiskey brand, in bonded form; bready rye and light citrus.",
    flavorProfile: fp({ spicy: 5, grain: 5, sweet: 4, woody: 4, fruity: 2, floral: 2 }), aliases: ["Overholt BiB"] },
  { id: "wild-turkey-101-rye", distilleryId: "wild-turkey", name: "Wild Turkey 101 Rye", category: "rye", region: "Kentucky",
    ageYears: null, abv: 50.5, caskTypes: ["new charred oak"], mashBill: "~52% rye, 21% corn, 27% malted barley", msrp: 30, avgPrice: 32,
    description: "Punchy, minty Kentucky rye that anchors a serious Manhattan.",
    flavorProfile: fp({ spicy: 7, sweet: 5, woody: 5, floral: 3, fruity: 2, grain: 2 }), aliases: ["WT Rye", "WT101 Rye"] },
  { id: "russells-reserve-6-rye", distilleryId: "wild-turkey", name: "Russell's Reserve 6 Year Rye", category: "rye", region: "Kentucky",
    ageYears: 6, abv: 45, caskTypes: ["new charred oak"], mashBill: "~52% rye, 21% corn, 27% malted barley", msrp: 45, avgPrice: 45,
    description: "Soft, sweet six-year rye with vanilla, orange, and gentle spice.",
    flavorProfile: fp({ spicy: 5, sweet: 6, fruity: 4, woody: 5, floral: 2, grain: 2 }), aliases: ["RR6 Rye"] },
  { id: "woodford-reserve-rye", distilleryId: "woodford-reserve", name: "Woodford Reserve Rye", category: "rye", region: "Kentucky",
    ageYears: null, abv: 45.2, caskTypes: ["new charred oak"], mashBill: "53% rye, 33% corn, 14% malted barley", msrp: 40, avgPrice: 38,
    description: "Low-rye, approachable rye with apple, clove, and honey.",
    flavorProfile: fp({ spicy: 5, fruity: 4, sweet: 5, woody: 5, grain: 3 }), aliases: ["Woodford Rye"] },
  { id: "old-forester-rye", distilleryId: "old-forester", name: "Old Forester Rye", category: "rye", region: "Kentucky",
    ageYears: null, abv: 50, caskTypes: ["new charred oak"], mashBill: "65% rye, 20% malted barley, 15% corn", msrp: 28, avgPrice: 28,
    description: "100-proof, 65% rye value monster; floral, peppery, and bright.",
    flavorProfile: fp({ spicy: 7, floral: 4, sweet: 5, woody: 4, grain: 3, fruity: 2 }), aliases: ["OF Rye"] },
  { id: "bulleit-rye", distilleryId: "bulleit", name: "Bulleit 95 Rye", category: "rye", region: "Indiana",
    ageYears: null, abv: 45, caskTypes: ["new charred oak"], mashBill: "95% rye, 5% malted barley", msrp: 30, avgPrice: 30,
    description: "The ubiquitous MGP 95/5 rye: dill, mint, and vanilla.",
    flavorProfile: fp({ spicy: 7, floral: 4, sweet: 4, woody: 4, grain: 2, fruity: 2 }), aliases: ["Bulleit Rye"] },
  { id: "michters-us1-rye", distilleryId: "michters", name: "Michter's US*1 Kentucky Straight Rye", category: "rye", region: "Kentucky",
    ageYears: null, abv: 42.4, caskTypes: ["new charred oak"], mashBill: "Single barrel rye (undisclosed)", msrp: 50, avgPrice: 50,
    description: "Single-barrel rye on the gentle end: butterscotch, citrus, and soft pepper.",
    flavorProfile: fp({ spicy: 5, sweet: 6, fruity: 4, woody: 4, grain: 2, floral: 2 }), aliases: ["Michters Rye"] },
  { id: "high-west-double-rye", distilleryId: "high-west", name: "High West Double Rye!", category: "rye", region: "Utah",
    ageYears: null, abv: 46, caskTypes: ["new charred oak"], mashBill: "Blend of 95/5 and high-rye whiskeys", msrp: 40, avgPrice: 40,
    description: "A blend of young spicy and older mellow ryes; mint, clove, and honey.",
    flavorProfile: fp({ spicy: 7, sweet: 5, floral: 3, woody: 4, fruity: 3, grain: 2 }), aliases: ["Double Rye"] },
  { id: "high-west-rendezvous-rye", distilleryId: "high-west", name: "High West Rendezvous Rye", category: "rye", region: "Utah",
    ageYears: null, abv: 46, caskTypes: ["new charred oak"], mashBill: "Blend of 95/5 and 80% rye whiskeys", msrp: 90, avgPrice: 80,
    description: "High West's flagship rye marriage; dark caramel, rye bread, and baking spice.",
    flavorProfile: fp({ spicy: 7, sweet: 6, woody: 5, fruity: 3, floral: 3, grain: 2 }), aliases: ["Rendezvous"] },
  { id: "whistlepig-10", distilleryId: "whistlepig", name: "WhistlePig 10 Year Small Batch Rye", category: "rye", region: "Vermont",
    ageYears: 10, abv: 50, caskTypes: ["new charred oak"], mashBill: "~100% Canadian rye", msrp: 90, avgPrice: 85,
    description: "The bottle that made aged rye luxurious; caramel, allspice, and orchard fruit.",
    flavorProfile: fp({ spicy: 7, sweet: 6, woody: 6, fruity: 4, floral: 2, feinty: 1 }), aliases: ["WP10", "WhistlePig 10"] },
  { id: "whistlepig-piggyback-6", distilleryId: "whistlepig", name: "WhistlePig PiggyBack 6 Year Rye", category: "rye", region: "Vermont",
    ageYears: 6, abv: 48.3, caskTypes: ["new charred oak"], mashBill: "100% rye", msrp: 55, avgPrice: 50,
    description: "Dave Pickerell's 100% rye built for cocktails; grassy, peppery, and clean.",
    flavorProfile: fp({ spicy: 7, floral: 4, grain: 3, sweet: 4, woody: 4, fruity: 2 }), aliases: ["PiggyBack"] },
  { id: "willett-family-estate-4-rye", distilleryId: "willett", name: "Willett Family Estate 4 Year Rye", category: "rye", region: "Kentucky",
    ageYears: 4, abv: 56, caskTypes: ["new charred oak"], mashBill: "74% rye, 11% corn, 15% malted barley", msrp: 70, avgPrice: 90,
    description: "Willett's own cask-strength rye; peppermint, cinnamon candy, and sweet dough.",
    flavorProfile: fp({ spicy: 8, sweet: 5, floral: 3, woody: 4, grain: 3, fruity: 2 }), aliases: ["WFE Rye", "Willett Rye"] },
  { id: "new-riff-bib-rye", distilleryId: "new-riff", name: "New Riff Bottled-in-Bond Rye", category: "rye", region: "Kentucky",
    ageYears: 4, abv: 50, caskTypes: ["new charred oak"], mashBill: "95% rye, 5% malted rye", msrp: 45, avgPrice: 45,
    description: "Malted-rye-finished 95% rye bond; spearmint, black tea, and molasses.",
    flavorProfile: fp({ spicy: 7, floral: 3, grain: 4, sweet: 4, woody: 4, fruity: 2 }), aliases: ["New Riff Rye"] },

  // =========================================================================
  // SCOTCH SINGLE MALT — Speyside
  // =========================================================================
  { id: "glenfiddich-12", distilleryId: "glenfiddich", name: "Glenfiddich 12", category: "scotch-single-malt", region: "Speyside",
    ageYears: 12, abv: 40, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 50, avgPrice: 45,
    description: "The world's best-selling single malt; fresh pear, apple, and light oak.",
    flavorProfile: fp({ fruity: 6, floral: 3, grain: 3, sweet: 5, woody: 3 }), aliases: ["Fiddich 12"] },
  { id: "glenfiddich-14", distilleryId: "glenfiddich", name: "Glenfiddich 14 Bourbon Barrel Reserve", category: "scotch-single-malt", region: "Speyside",
    ageYears: 14, abv: 43, caskTypes: ["ex-bourbon", "new charred oak"], msrp: 60, avgPrice: 60,
    description: "US-market release finished in new charred oak; vanilla, baked apple, and toffee.",
    flavorProfile: fp({ sweet: 6, fruity: 5, woody: 5, grain: 3, floral: 2 }), aliases: ["Glenfiddich 14 BBR"] },
  { id: "glenfiddich-15", distilleryId: "glenfiddich", name: "Glenfiddich 15 Solera", category: "scotch-single-malt", region: "Speyside",
    ageYears: 15, abv: 40, caskTypes: ["ex-bourbon", "oloroso sherry", "new oak (solera vat)"], msrp: 75, avgPrice: 70,
    description: "Married in a solera vat; honey, raisin, and soft spice.",
    flavorProfile: fp({ fruity: 6, sweet: 6, woody: 4, spicy: 3, grain: 2, floral: 2 }), aliases: ["Glenfiddich Solera"] },
  { id: "glenfiddich-18", distilleryId: "glenfiddich", name: "Glenfiddich 18", category: "scotch-single-malt", region: "Speyside",
    ageYears: 18, abv: 40, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 130, avgPrice: 120,
    description: "Baked apple, candied peel, and polished oak in a stately Speyside package.",
    flavorProfile: fp({ fruity: 6, sweet: 6, woody: 6, spicy: 3, grain: 2 }), aliases: [] },
  { id: "glenlivet-12", distilleryId: "glenlivet", name: "The Glenlivet 12", category: "scotch-single-malt", region: "Speyside",
    ageYears: 12, abv: 40, caskTypes: ["ex-bourbon", "european oak"], msrp: 45, avgPrice: 42,
    description: "The definitive gentle Speysider: honey, citrus blossom, and vanilla cream.",
    flavorProfile: fp({ fruity: 5, floral: 4, sweet: 5, grain: 3, woody: 2 }), aliases: ["Glenlivet 12"] },
  { id: "glenlivet-18", distilleryId: "glenlivet", name: "The Glenlivet 18", category: "scotch-single-malt", region: "Speyside",
    ageYears: 18, abv: 43, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 130, avgPrice: 120,
    description: "Orange marmalade, toffee, and oak spice with classic Glenlivet elegance.",
    flavorProfile: fp({ fruity: 6, sweet: 6, woody: 5, spicy: 3, floral: 3 }), aliases: [] },
  { id: "macallan-12-sherry", distilleryId: "macallan", name: "The Macallan 12 Sherry Oak", category: "scotch-single-malt", region: "Speyside",
    ageYears: 12, abv: 43, caskTypes: ["oloroso sherry"], msrp: 95, avgPrice: 90,
    description: "Matured fully in sherry-seasoned oak; dried fruit, ginger, and chocolate orange.",
    flavorProfile: fp({ fruity: 8, sweet: 7, woody: 5, spicy: 4, grain: 1, feinty: 1 }), aliases: ["Mac 12", "Macallan Sherry Oak 12"] },
  { id: "macallan-12-double-cask", distilleryId: "macallan", name: "The Macallan 12 Double Cask", category: "scotch-single-malt", region: "Speyside",
    ageYears: 12, abv: 43, caskTypes: ["american oak sherry", "european oak sherry"], msrp: 85, avgPrice: 80,
    description: "American and European sherry oak married for a creamier, vanilla-led Macallan.",
    flavorProfile: fp({ fruity: 6, sweet: 7, woody: 4, spicy: 3, grain: 2 }), aliases: ["Mac 12 DC"] },
  { id: "macallan-18-sherry", distilleryId: "macallan", name: "The Macallan 18 Sherry Oak", category: "scotch-single-malt", region: "Speyside",
    ageYears: 18, abv: 43, caskTypes: ["oloroso sherry"], msrp: 400, avgPrice: 380,
    description: "The status-symbol sherry bomb: fig, clove, mahogany, and long dried-fruit finish.",
    flavorProfile: fp({ fruity: 8, sweet: 7, woody: 7, spicy: 4, feinty: 2 }), aliases: ["Mac 18"] },
  { id: "balvenie-12-doublewood", distilleryId: "balvenie", name: "The Balvenie DoubleWood 12", category: "scotch-single-malt", region: "Speyside",
    ageYears: 12, abv: 40, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 70, avgPrice: 65,
    description: "Bourbon-cask honey finished in sherry butts; nutty, layered, endlessly drinkable.",
    flavorProfile: fp({ sweet: 6, fruity: 5, woody: 4, grain: 3, spicy: 3, floral: 2 }), aliases: ["DoubleWood", "Balvenie 12"] },
  { id: "balvenie-14-caribbean", distilleryId: "balvenie", name: "The Balvenie Caribbean Cask 14", category: "scotch-single-malt", region: "Speyside",
    ageYears: 14, abv: 43, caskTypes: ["ex-bourbon", "rum"], msrp: 90, avgPrice: 85,
    description: "Rum-cask finish adds banana, toffee, and tropical sweetness to the honeyed house style.",
    flavorProfile: fp({ sweet: 7, fruity: 6, woody: 4, grain: 2, spicy: 2, floral: 1 }), aliases: ["Balvenie 14", "Caribbean Cask"] },
  { id: "glenfarclas-12", distilleryId: "glenfarclas", name: "Glenfarclas 12", category: "scotch-single-malt", region: "Speyside",
    ageYears: 12, abv: 43, caskTypes: ["oloroso sherry"], msrp: 65, avgPrice: 60,
    description: "Honest family-made sherried Speyside: sultana, malt, and a whiff of struck match.",
    flavorProfile: fp({ fruity: 6, sweet: 6, grain: 3, woody: 4, spicy: 3, feinty: 2 }), aliases: [] },
  { id: "glenfarclas-105", distilleryId: "glenfarclas", name: "Glenfarclas 105 Cask Strength", category: "scotch-single-malt", region: "Speyside",
    ageYears: null, abv: 60, caskTypes: ["oloroso sherry"], msrp: 90, avgPrice: 85,
    description: "The original cask-strength sherried malt at 60%; Christmas cake with a burn.",
    flavorProfile: fp({ fruity: 7, sweet: 7, spicy: 5, woody: 5, feinty: 2, grain: 1 }), aliases: ["105"] },
  { id: "glenfarclas-25", distilleryId: "glenfarclas", name: "Glenfarclas 25", category: "scotch-single-malt", region: "Speyside",
    ageYears: 25, abv: 43, caskTypes: ["oloroso sherry"], msrp: 190, avgPrice: 200,
    description: "A quarter century of sherry maturation at a famously fair price; walnut, espresso, and fig.",
    flavorProfile: fp({ fruity: 7, woody: 7, sweet: 6, spicy: 4, feinty: 3 }), aliases: [] },
  { id: "aberlour-12", distilleryId: "aberlour", name: "Aberlour 12 Double Cask", category: "scotch-single-malt", region: "Speyside",
    ageYears: 12, abv: 40, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 55, avgPrice: 50,
    description: "Approachable double-cask Speysider; red apple, chocolate, and gentle spice.",
    flavorProfile: fp({ fruity: 6, sweet: 6, woody: 4, spicy: 3, grain: 2 }), aliases: [] },
  { id: "aberlour-abunadh", distilleryId: "aberlour", name: "Aberlour A'bunadh", category: "scotch-single-malt", region: "Speyside",
    ageYears: null, abv: 60.9, caskTypes: ["oloroso sherry"], msrp: 100, avgPrice: 95,
    description: "Batch-released cask-strength sherry bomb; raisin, orange oil, dark chocolate, and heat.",
    flavorProfile: fp({ fruity: 8, sweet: 8, spicy: 5, woody: 5, feinty: 2 }), aliases: ["A'bunadh", "Abunadh"] },

  // --- Scotch single malt: Highland ---
  { id: "glenmorangie-10", distilleryId: "glenmorangie", name: "Glenmorangie Original 10", category: "scotch-single-malt", region: "Highland",
    ageYears: 10, abv: 40, caskTypes: ["ex-bourbon"], msrp: 45, avgPrice: 40,
    description: "Tall-still delicacy: citrus, peach, vanilla, and white flowers.",
    flavorProfile: fp({ fruity: 6, floral: 5, sweet: 5, grain: 3, woody: 2 }), aliases: ["Glenmo 10", "Glenmorangie Original"] },
  { id: "glenmorangie-lasanta", distilleryId: "glenmorangie", name: "Glenmorangie Lasanta 12", category: "scotch-single-malt", region: "Highland",
    ageYears: 12, abv: 43, caskTypes: ["ex-bourbon", "oloroso sherry", "PX sherry"], msrp: 55, avgPrice: 50,
    description: "Sherry-finished Glenmorangie; toffee, sultana, and honeycomb.",
    flavorProfile: fp({ fruity: 6, sweet: 7, woody: 4, spicy: 3, floral: 2 }), aliases: ["Lasanta"] },
  { id: "glenmorangie-signet", distilleryId: "glenmorangie", name: "Glenmorangie Signet", category: "scotch-single-malt", region: "Highland",
    ageYears: null, abv: 46, caskTypes: ["ex-bourbon", "new charred oak", "oloroso sherry"], msrp: 250, avgPrice: 230,
    description: "Built on high-roast chocolate malt; espresso, mocha, and candied orange — utterly distinctive.",
    flavorProfile: fp({ sweet: 7, woody: 6, fruity: 6, grain: 5, spicy: 4, feinty: 1 }), aliases: ["Signet"] },
  { id: "glendronach-12", distilleryId: "glendronach", name: "The GlenDronach Original 12", category: "scotch-single-malt", region: "Highland",
    ageYears: 12, abv: 43, caskTypes: ["PX sherry", "oloroso sherry"], msrp: 70, avgPrice: 65,
    description: "Rich sherried Highlander: stewed plum, cocoa, and brown sugar.",
    flavorProfile: fp({ fruity: 7, sweet: 7, woody: 5, spicy: 3, feinty: 2 }), aliases: ["Dronach 12"] },
  { id: "glendronach-15", distilleryId: "glendronach", name: "The GlenDronach Revival 15", category: "scotch-single-malt", region: "Highland",
    ageYears: 15, abv: 46, caskTypes: ["PX sherry", "oloroso sherry"], msrp: 100, avgPrice: 95,
    description: "The cult favorite Revival; fig jam, dark chocolate, walnut, and leather.",
    flavorProfile: fp({ fruity: 8, sweet: 7, woody: 6, spicy: 4, feinty: 3 }), aliases: ["Revival"] },
  { id: "glendronach-18", distilleryId: "glendronach", name: "The GlenDronach Allardice 18", category: "scotch-single-malt", region: "Highland",
    ageYears: 18, abv: 46, caskTypes: ["oloroso sherry"], msrp: 180, avgPrice: 170,
    description: "Deep oloroso maturation; treacle, black cherry, tobacco, and old oak.",
    flavorProfile: fp({ fruity: 8, sweet: 7, woody: 7, spicy: 4, feinty: 3 }), aliases: ["Allardice"] },
  { id: "dalmore-12", distilleryId: "dalmore", name: "The Dalmore 12", category: "scotch-single-malt", region: "Highland",
    ageYears: 12, abv: 40, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 70, avgPrice: 65,
    description: "Orange, chocolate, and Christmas spice under the royal stag.",
    flavorProfile: fp({ fruity: 6, sweet: 7, woody: 5, spicy: 3, feinty: 1 }), aliases: [] },
  { id: "oban-14", distilleryId: "oban", name: "Oban 14", category: "scotch-single-malt", region: "Highland",
    ageYears: 14, abv: 43, caskTypes: ["ex-bourbon"], msrp: 90, avgPrice: 85,
    description: "West Highland harbor malt: orange peel, sea salt, honey, and a wisp of smoke.",
    flavorProfile: fp({ fruity: 6, sweet: 5, peaty: 3, woody: 4, floral: 2, grain: 2, feinty: 1 }), aliases: [] },

  // --- Scotch single malt: Islands & Campbeltown & Lowland ---
  { id: "highland-park-12", distilleryId: "highland-park", name: "Highland Park 12 Viking Honour", category: "scotch-single-malt", region: "Islands",
    ageYears: 12, abv: 43, caskTypes: ["sherry-seasoned european oak", "sherry-seasoned american oak"], msrp: 65, avgPrice: 60,
    description: "Orkney balance of heather honey, dried fruit, and gentle floor-malt smoke.",
    flavorProfile: fp({ sweet: 6, fruity: 5, peaty: 4, floral: 4, woody: 4, grain: 2 }), aliases: ["HP12"] },
  { id: "highland-park-18", distilleryId: "highland-park", name: "Highland Park 18 Viking Pride", category: "scotch-single-malt", region: "Islands",
    ageYears: 18, abv: 43, caskTypes: ["sherry-seasoned european oak"], msrp: 180, avgPrice: 170,
    description: "Layered honeyed smoke and dark fruit; a perennial top-shelf favorite.",
    flavorProfile: fp({ sweet: 7, fruity: 6, peaty: 4, woody: 6, floral: 3, feinty: 2 }), aliases: ["HP18"] },
  { id: "talisker-10", distilleryId: "talisker", name: "Talisker 10", category: "scotch-single-malt", region: "Islands",
    ageYears: 10, abv: 45.8, caskTypes: ["ex-bourbon"], msrp: 70, avgPrice: 65,
    description: "Skye's maritime classic: black pepper, brine, and campfire embers.",
    flavorProfile: fp({ peaty: 6, spicy: 6, sweet: 4, fruity: 4, feinty: 2, grain: 2 }), aliases: [] },
  { id: "talisker-18", distilleryId: "talisker", name: "Talisker 18", category: "scotch-single-malt", region: "Islands",
    ageYears: 18, abv: 45.8, caskTypes: ["ex-bourbon", "sherry"], msrp: 180, avgPrice: 190,
    description: "Once voted best single malt in the world; mellowed smoke, toffee, and sea spray.",
    flavorProfile: fp({ peaty: 5, sweet: 6, fruity: 5, woody: 5, spicy: 4, feinty: 2 }), aliases: [] },
  { id: "springbank-10", distilleryId: "springbank", name: "Springbank 10", category: "scotch-single-malt", region: "Campbeltown",
    ageYears: 10, abv: 46, caskTypes: ["ex-bourbon", "sherry"], msrp: 75, avgPrice: 110,
    description: "Lightly peated, oily Campbeltown funk: brine, wax, and orchard fruit.",
    flavorProfile: fp({ fruity: 5, peaty: 4, feinty: 5, grain: 4, sweet: 4, woody: 3 }), aliases: ["SB10"] },
  { id: "springbank-15", distilleryId: "springbank", name: "Springbank 15", category: "scotch-single-malt", region: "Campbeltown",
    ageYears: 15, abv: 46, caskTypes: ["sherry"], msrp: 140, avgPrice: 200,
    description: "Sherried Springbank with dark chocolate, dunnage earth, and leather.",
    flavorProfile: fp({ fruity: 6, feinty: 5, peaty: 4, sweet: 5, woody: 5, spicy: 3 }), aliases: [] },
  { id: "longrow-peated", distilleryId: "springbank", name: "Longrow Peated", category: "scotch-single-malt", region: "Campbeltown",
    ageYears: null, abv: 46, caskTypes: ["ex-bourbon", "sherry"], msrp: 60, avgPrice: 90,
    description: "Springbank's double-distilled heavily peated line; smoky, meaty, coastal.",
    flavorProfile: fp({ peaty: 7, feinty: 4, fruity: 4, sweet: 4, grain: 3, spicy: 3 }), aliases: [] },
  { id: "auchentoshan-12", distilleryId: "auchentoshan", name: "Auchentoshan 12", category: "scotch-single-malt", region: "Lowland",
    ageYears: 12, abv: 40, caskTypes: ["ex-bourbon", "sherry"], msrp: 55, avgPrice: 50,
    description: "Triple-distilled Lowland lightness: almond, citrus, and toasted grain.",
    flavorProfile: fp({ grain: 5, fruity: 5, sweet: 5, floral: 3, woody: 3 }), aliases: [] },
  { id: "auchentoshan-three-wood", distilleryId: "auchentoshan", name: "Auchentoshan Three Wood", category: "scotch-single-malt", region: "Lowland",
    ageYears: null, abv: 43, caskTypes: ["ex-bourbon", "oloroso sherry", "PX sherry"], msrp: 80, avgPrice: 75,
    description: "Triple-cask, triple-distilled; brown sugar, raisin, and hazelnut.",
    flavorProfile: fp({ sweet: 7, fruity: 6, woody: 4, grain: 3, spicy: 2 }), aliases: ["Three Wood"] },

  // --- Scotch single malt: Islay ---
  { id: "lagavulin-8", distilleryId: "lagavulin", name: "Lagavulin 8", category: "scotch-single-malt", region: "Islay",
    ageYears: 8, abv: 48, caskTypes: ["ex-bourbon"], msrp: 70, avgPrice: 65,
    description: "Younger, punchier Lagavulin; ashy smoke, citrus, and sea salt.",
    flavorProfile: fp({ peaty: 8, sweet: 4, fruity: 3, spicy: 3, grain: 2, feinty: 2 }), aliases: ["Laga 8"] },
  { id: "lagavulin-16", distilleryId: "lagavulin", name: "Lagavulin 16", category: "scotch-single-malt", region: "Islay",
    ageYears: 16, abv: 43, caskTypes: ["ex-bourbon", "sherry"], msrp: 110, avgPrice: 100,
    description: "The definitive rich Islay dram: lapsang smoke, iodine, dried fruit, and sweet peat.",
    flavorProfile: fp({ peaty: 9, sweet: 5, fruity: 5, woody: 5, feinty: 3, spicy: 3 }), aliases: ["Laga 16", "Lag 16"] },
  { id: "lagavulin-distillers-edition", distilleryId: "lagavulin", name: "Lagavulin Distillers Edition", category: "scotch-single-malt", region: "Islay",
    ageYears: 16, abv: 43, caskTypes: ["ex-bourbon", "PX sherry"], msrp: 150, avgPrice: 140,
    description: "Lagavulin 16 finished in PX casks; smoked raisin and treacle.",
    flavorProfile: fp({ peaty: 8, sweet: 7, fruity: 6, woody: 5, feinty: 3 }), aliases: ["Laga DE"] },
  { id: "laphroaig-10", distilleryId: "laphroaig", name: "Laphroaig 10", category: "scotch-single-malt", region: "Islay",
    ageYears: 10, abv: 43, caskTypes: ["ex-bourbon"], msrp: 55, avgPrice: 50,
    description: "Love-it-or-hate-it medicinal Islay: iodine, seaweed, tar, and vanilla underneath.",
    flavorProfile: fp({ peaty: 9, feinty: 3, sweet: 3, fruity: 2, grain: 2, spicy: 2 }), aliases: ["Frog 10", "Laphroaig Ten"] },
  { id: "laphroaig-quarter-cask", distilleryId: "laphroaig", name: "Laphroaig Quarter Cask", category: "scotch-single-malt", region: "Islay",
    ageYears: null, abv: 48, caskTypes: ["ex-bourbon", "quarter cask"], msrp: 65, avgPrice: 60,
    description: "Small-cask finish doubles the oak contact; sweeter, spicier, still unmistakably Laphroaig.",
    flavorProfile: fp({ peaty: 9, sweet: 5, woody: 5, spicy: 3, fruity: 2, feinty: 3 }), aliases: ["QC", "Laphroaig QC"] },
  { id: "laphroaig-lore", distilleryId: "laphroaig", name: "Laphroaig Lore", category: "scotch-single-malt", region: "Islay",
    ageYears: null, abv: 48, caskTypes: ["ex-bourbon", "quarter cask", "oloroso sherry"], msrp: 140, avgPrice: 130,
    description: "'The richest of the rich' — layered smoke, dark chocolate, and chili oak.",
    flavorProfile: fp({ peaty: 9, sweet: 6, woody: 6, fruity: 4, spicy: 4, feinty: 3 }), aliases: ["Lore"] },
  { id: "ardbeg-10", distilleryId: "ardbeg", name: "Ardbeg 10", category: "scotch-single-malt", region: "Islay",
    ageYears: 10, abv: 46, caskTypes: ["ex-bourbon"], msrp: 55, avgPrice: 55,
    description: "Intensely smoky yet lifted: tar and bonfire wrapped around lime and cream.",
    flavorProfile: fp({ peaty: 10, fruity: 4, sweet: 4, grain: 2, floral: 2, feinty: 2 }), aliases: ["Ardbeg Ten"] },
  { id: "ardbeg-uigeadail", distilleryId: "ardbeg", name: "Ardbeg Uigeadail", category: "scotch-single-malt", region: "Islay",
    ageYears: null, abv: 54.2, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 85, avgPrice: 80,
    description: "Cask-strength marriage of smoke and sherry; raisin, treacle, and peat embers.",
    flavorProfile: fp({ peaty: 9, sweet: 6, fruity: 6, woody: 4, feinty: 3, spicy: 3 }), aliases: ["Oogie", "Uigy"] },
  { id: "ardbeg-corryvreckan", distilleryId: "ardbeg", name: "Ardbeg Corryvreckan", category: "scotch-single-malt", region: "Islay",
    ageYears: null, abv: 57.1, caskTypes: ["ex-bourbon", "french oak"], msrp: 95, avgPrice: 90,
    description: "Named for the whirlpool; peppery, inky, espresso-dark peat at full throttle.",
    flavorProfile: fp({ peaty: 10, spicy: 6, fruity: 4, sweet: 4, woody: 4, feinty: 3 }), aliases: ["Corry"] },
  { id: "bowmore-12", distilleryId: "bowmore", name: "Bowmore 12", category: "scotch-single-malt", region: "Islay",
    ageYears: 12, abv: 40, caskTypes: ["ex-bourbon", "sherry"], msrp: 60, avgPrice: 55,
    description: "Mid-peated Islay gateway: honey, citrus, and gentle harbor smoke.",
    flavorProfile: fp({ peaty: 6, sweet: 5, fruity: 4, floral: 3, woody: 3, grain: 2 }), aliases: [] },
  { id: "bowmore-15", distilleryId: "bowmore", name: "Bowmore 15 Darkest", category: "scotch-single-malt", region: "Islay",
    ageYears: 15, abv: 43, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 100, avgPrice: 95,
    description: "Sherry-finished Bowmore: chocolate raisin, toffee, and soft peat.",
    flavorProfile: fp({ peaty: 6, sweet: 6, fruity: 6, woody: 5, feinty: 2 }), aliases: [] },
  { id: "bruichladdich-classic-laddie", distilleryId: "bruichladdich", name: "Bruichladdich The Classic Laddie", category: "scotch-single-malt", region: "Islay",
    ageYears: null, abv: 50, caskTypes: ["ex-bourbon"], msrp: 65, avgPrice: 60,
    description: "Unpeated Islay in the aqua bottle: barley sugar, lemon, and sea breeze.",
    flavorProfile: fp({ grain: 5, fruity: 5, floral: 4, sweet: 5, woody: 2, feinty: 1 }), aliases: ["Classic Laddie", "Laddie"] },
  { id: "port-charlotte-10", distilleryId: "bruichladdich", name: "Port Charlotte 10", category: "scotch-single-malt", region: "Islay",
    ageYears: 10, abv: 50, caskTypes: ["ex-bourbon", "wine"], msrp: 75, avgPrice: 70,
    description: "Heavily peated Bruichladdich; elegant smoke over malt syrup and citrus.",
    flavorProfile: fp({ peaty: 8, sweet: 5, fruity: 4, grain: 3, woody: 3, feinty: 2 }), aliases: ["PC10"] },
  { id: "bunnahabhain-12", distilleryId: "bunnahabhain", name: "Bunnahabhain 12", category: "scotch-single-malt", region: "Islay",
    ageYears: 12, abv: 46.3, caskTypes: ["ex-bourbon", "sherry"], msrp: 80, avgPrice: 70,
    description: "The gentle Islay: nutty sherry, brine, and toffee with barely-there smoke.",
    flavorProfile: fp({ fruity: 6, sweet: 6, feinty: 2, woody: 4, grain: 3, peaty: 1 }), aliases: ["Bunna 12"] },
  { id: "caol-ila-12", distilleryId: "caol-ila", name: "Caol Ila 12", category: "scotch-single-malt", region: "Islay",
    ageYears: 12, abv: 43, caskTypes: ["ex-bourbon"], msrp: 80, avgPrice: 70,
    description: "Grassy, citrusy Islay smoke — lighter-bodied than its Kildalton neighbors.",
    flavorProfile: fp({ peaty: 7, fruity: 4, floral: 3, sweet: 4, grain: 3, feinty: 1 }), aliases: [] },
  { id: "kilchoman-machir-bay", distilleryId: "kilchoman", name: "Kilchoman Machir Bay", category: "scotch-single-malt", region: "Islay",
    ageYears: null, abv: 46, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 65, avgPrice: 60,
    description: "Farm-distillery flagship; crisp lemon, vanilla, and fresh peat smoke.",
    flavorProfile: fp({ peaty: 7, fruity: 4, sweet: 4, grain: 3, floral: 2, feinty: 1 }), aliases: ["Machir Bay"] },

  // =========================================================================
  // SCOTCH BLENDED
  // =========================================================================
  { id: "johnnie-walker-red", distilleryId: "johnnie-walker", name: "Johnnie Walker Red Label", category: "scotch-blended", region: "Scotland",
    ageYears: null, abv: 40, caskTypes: ["refill oak"], msrp: 25, avgPrice: 22,
    description: "The world's best-selling Scotch; built for highballs with brisk smoke and spice.",
    flavorProfile: fp({ grain: 5, spicy: 4, peaty: 3, sweet: 4, fruity: 3 }), aliases: ["JW Red"] },
  { id: "johnnie-walker-black", distilleryId: "johnnie-walker", name: "Johnnie Walker Black Label 12", category: "scotch-blended", region: "Scotland",
    ageYears: 12, abv: 40, caskTypes: ["refill oak"], msrp: 40, avgPrice: 35,
    description: "The benchmark blend: dried fruit, vanilla, and a signature wisp of Islay smoke.",
    flavorProfile: fp({ sweet: 5, fruity: 5, peaty: 4, grain: 4, woody: 4, spicy: 3 }), aliases: ["JW Black", "JWB"] },
  { id: "johnnie-walker-green", distilleryId: "johnnie-walker", name: "Johnnie Walker Green Label 15", category: "scotch-blended", region: "Scotland",
    ageYears: 15, abv: 43, caskTypes: ["refill oak"], msrp: 75, avgPrice: 70,
    description: "All-malt blend of Talisker, Caol Ila, Linkwood, and Cragganmore; herbal, smoky, honeyed.",
    flavorProfile: fp({ fruity: 5, peaty: 4, sweet: 5, floral: 4, grain: 3, woody: 4 }), aliases: ["JW Green"] },
  { id: "johnnie-walker-blue", distilleryId: "johnnie-walker", name: "Johnnie Walker Blue Label", category: "scotch-blended", region: "Scotland",
    ageYears: null, abv: 40, caskTypes: ["refill oak"], msrp: 250, avgPrice: 230,
    description: "Luxury blend of rare stocks; silky honey, hazelnut, and polished smoke.",
    flavorProfile: fp({ sweet: 6, fruity: 5, peaty: 3, woody: 5, spicy: 3, feinty: 1 }), aliases: ["JW Blue", "Blue Label"] },
  { id: "chivas-regal-12", distilleryId: "chivas-brothers", name: "Chivas Regal 12", category: "scotch-blended", region: "Scotland",
    ageYears: 12, abv: 40, caskTypes: ["refill oak"], msrp: 35, avgPrice: 32,
    description: "Strathisla-hearted smooth blend; honey, apple, and hazelnut.",
    flavorProfile: fp({ sweet: 5, fruity: 5, grain: 4, floral: 3, woody: 3 }), aliases: ["Chivas 12"] },
  { id: "ballantines-finest", distilleryId: "chivas-brothers", name: "Ballantine's Finest", category: "scotch-blended", region: "Scotland",
    ageYears: null, abv: 40, caskTypes: ["refill oak"], msrp: 25, avgPrice: 22,
    description: "One of the world's biggest blends; light toffee, red apple, and gentle spice.",
    flavorProfile: fp({ grain: 5, sweet: 5, fruity: 4, floral: 3, spicy: 2 }), aliases: ["Ballantines"] },
  { id: "dewars-12", distilleryId: "dewars", name: "Dewar's 12 The Ancestor", category: "scotch-blended", region: "Scotland",
    ageYears: 12, abv: 40, caskTypes: ["refill oak"], msrp: 30, avgPrice: 28,
    description: "Double-aged Aberfeldy-led blend; heather honey, malt, and soft oak.",
    flavorProfile: fp({ sweet: 6, grain: 4, fruity: 4, floral: 3, woody: 3 }), aliases: ["Dewars 12"] },
  { id: "monkey-shoulder", distilleryId: "william-grant-sons", name: "Monkey Shoulder", category: "scotch-blended", region: "Scotland",
    ageYears: null, abv: 43, caskTypes: ["ex-bourbon"], msrp: 35, avgPrice: 32,
    description: "Blended-malt mixing staple from Speyside malts; malty, vanilla-rich, and round.",
    flavorProfile: fp({ sweet: 6, grain: 5, fruity: 4, floral: 2, woody: 3 }), aliases: [] },
  { id: "compass-box-spice-tree", distilleryId: "compass-box", name: "Compass Box The Spice Tree", category: "scotch-blended", region: "Scotland",
    ageYears: null, abv: 46, caskTypes: ["french oak (heavy toast)"], msrp: 70, avgPrice: 65,
    description: "Blended malt finished on heavily toasted French oak heads; clove, ginger, and baked fruit.",
    flavorProfile: fp({ spicy: 6, sweet: 6, woody: 5, fruity: 5, grain: 2 }), aliases: ["Spice Tree"] },
  { id: "compass-box-peat-monster", distilleryId: "compass-box", name: "Compass Box The Peat Monster", category: "scotch-blended", region: "Scotland",
    ageYears: null, abv: 46, caskTypes: ["refill oak"], msrp: 65, avgPrice: 60,
    description: "Islay and Highland smoke assembled with Compass Box polish.",
    flavorProfile: fp({ peaty: 8, fruity: 4, sweet: 4, grain: 3, spicy: 3, feinty: 2 }), aliases: ["Peat Monster"] },

  // =========================================================================
  // IRISH
  // =========================================================================
  { id: "jameson", distilleryId: "midleton", name: "Jameson Irish Whiskey", category: "irish", region: "Cork",
    ageYears: null, abv: 40, caskTypes: ["ex-bourbon", "sherry"], msrp: 35, avgPrice: 30,
    description: "The world's best-selling Irish whiskey; triple-distilled, light, and toasty.",
    flavorProfile: fp({ grain: 5, sweet: 5, fruity: 4, floral: 2, woody: 2 }), aliases: ["Jamo"] },
  { id: "jameson-black-barrel", distilleryId: "midleton", name: "Jameson Black Barrel", category: "irish", region: "Cork",
    ageYears: null, abv: 40, caskTypes: ["double-charred ex-bourbon", "sherry"], msrp: 45, avgPrice: 40,
    description: "Double-charred casks add butterscotch and toasted nut depth to the Jameson core.",
    flavorProfile: fp({ sweet: 6, grain: 4, fruity: 4, woody: 4, spicy: 2 }), aliases: ["Black Barrel"] },
  { id: "redbreast-12", distilleryId: "midleton", name: "Redbreast 12", category: "irish", region: "Cork",
    ageYears: 12, abv: 40, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 70, avgPrice: 65,
    description: "The benchmark single pot still: baked orchard fruit, sherry nut, and pot-still spice.",
    flavorProfile: fp({ fruity: 7, sweet: 6, spicy: 5, grain: 4, woody: 4, feinty: 1 }), aliases: ["RB12"] },
  { id: "redbreast-12-cask-strength", distilleryId: "midleton", name: "Redbreast 12 Cask Strength", category: "irish", region: "Cork",
    ageYears: 12, abv: 57.2, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 100, avgPrice: 95,
    description: "Full-strength Redbreast; the same fruit-and-spice profile with the volume turned up.",
    flavorProfile: fp({ fruity: 8, spicy: 6, sweet: 6, woody: 5, grain: 3, feinty: 1 }), aliases: ["RB12CS"] },
  { id: "redbreast-15", distilleryId: "midleton", name: "Redbreast 15", category: "irish", region: "Cork",
    ageYears: 15, abv: 46, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 130, avgPrice: 120,
    description: "Older pot still depth: fig, clove, dark chocolate, and oily texture.",
    flavorProfile: fp({ fruity: 7, sweet: 6, spicy: 5, woody: 6, grain: 3, feinty: 2 }), aliases: ["RB15"] },
  { id: "redbreast-lustau", distilleryId: "midleton", name: "Redbreast Lustau Edition", category: "irish", region: "Cork",
    ageYears: null, abv: 46, caskTypes: ["ex-bourbon", "oloroso sherry", "Lustau sherry finish"], msrp: 80, avgPrice: 75,
    description: "Finished in fresh Bodegas Lustau sherry butts; marzipan, raisin, and salted toffee.",
    flavorProfile: fp({ fruity: 7, sweet: 7, spicy: 4, woody: 4, grain: 3, feinty: 1 }), aliases: ["Lustau"] },
  { id: "green-spot", distilleryId: "midleton", name: "Green Spot", category: "irish", region: "Cork",
    ageYears: null, abv: 40, caskTypes: ["ex-bourbon", "sherry"], msrp: 65, avgPrice: 60,
    description: "The bonder's classic single pot still; green apple, menthol, and barley sugar.",
    flavorProfile: fp({ fruity: 6, grain: 5, sweet: 5, spicy: 4, floral: 3 }), aliases: [] },
  { id: "yellow-spot-12", distilleryId: "midleton", name: "Yellow Spot 12", category: "irish", region: "Cork",
    ageYears: 12, abv: 46, caskTypes: ["ex-bourbon", "sherry", "Malaga wine"], msrp: 110, avgPrice: 100,
    description: "Malaga-cask pot still; honeyed apricot, mown hay, and clove.",
    flavorProfile: fp({ fruity: 7, sweet: 7, spicy: 4, grain: 3, woody: 4, floral: 2 }), aliases: [] },
  { id: "powers-gold-label", distilleryId: "midleton", name: "Powers Gold Label", category: "irish", region: "Cork",
    ageYears: null, abv: 43.2, caskTypes: ["ex-bourbon"], msrp: 35, avgPrice: 32,
    description: "Dublin's working whiskey with a high pot-still charge; honey, white pepper, and malt.",
    flavorProfile: fp({ grain: 5, spicy: 5, sweet: 5, fruity: 4, woody: 2 }), aliases: ["Powers Gold"] },
  { id: "powers-johns-lane-12", distilleryId: "midleton", name: "Powers John's Lane 12", category: "irish", region: "Cork",
    ageYears: 12, abv: 46, caskTypes: ["ex-bourbon", "oloroso sherry"], msrp: 80, avgPrice: 75,
    description: "A muscular single pot still tribute to the old Dublin distillery; leather, toffee, and earthy spice.",
    flavorProfile: fp({ spicy: 6, sweet: 6, fruity: 5, woody: 5, grain: 3, feinty: 2 }), aliases: ["Johns Lane"] },
  { id: "midleton-very-rare", distilleryId: "midleton", name: "Midleton Very Rare", category: "irish", region: "Cork",
    ageYears: null, abv: 40, caskTypes: ["ex-bourbon"], msrp: 250, avgPrice: 220,
    description: "The annual prestige Irish blend; silky vanilla, green fruit, and gentle spice.",
    flavorProfile: fp({ sweet: 6, fruity: 6, grain: 4, woody: 4, floral: 3, spicy: 3 }), aliases: ["MVR"] },
  { id: "bushmills-original", distilleryId: "bushmills", name: "Bushmills Original", category: "irish", region: "County Antrim",
    ageYears: null, abv: 40, caskTypes: ["ex-bourbon", "sherry"], msrp: 25, avgPrice: 22,
    description: "The white-label Antrim blend; light, grassy, and gently sweet.",
    flavorProfile: fp({ grain: 5, sweet: 4, fruity: 4, floral: 2, woody: 2 }), aliases: ["Bushmills White"] },
  { id: "bushmills-black-bush", distilleryId: "bushmills", name: "Bushmills Black Bush", category: "irish", region: "County Antrim",
    ageYears: null, abv: 40, caskTypes: ["oloroso sherry", "ex-bourbon"], msrp: 35, avgPrice: 30,
    description: "High-malt, sherry-led blend; dark fruit and toasted nut at a bargain.",
    flavorProfile: fp({ fruity: 6, sweet: 6, grain: 4, woody: 3, feinty: 1 }), aliases: ["Black Bush"] },
  { id: "bushmills-10", distilleryId: "bushmills", name: "Bushmills 10 Single Malt", category: "irish", region: "County Antrim",
    ageYears: 10, abv: 40, caskTypes: ["ex-bourbon", "sherry"], msrp: 45, avgPrice: 40,
    description: "Triple-distilled Irish single malt; honey, vanilla, and ripe banana.",
    flavorProfile: fp({ fruity: 5, sweet: 6, grain: 4, floral: 3, woody: 3 }), aliases: [] },
  { id: "bushmills-16", distilleryId: "bushmills", name: "Bushmills 16 Single Malt", category: "irish", region: "County Antrim",
    ageYears: 16, abv: 40, caskTypes: ["ex-bourbon", "oloroso sherry", "port"], msrp: 90, avgPrice: 85,
    description: "Three-wood Irish malt finished in port pipes; juicy red fruit and milk chocolate.",
    flavorProfile: fp({ fruity: 7, sweet: 7, woody: 5, grain: 2, spicy: 2, feinty: 1 }), aliases: [] },
  { id: "teeling-small-batch", distilleryId: "teeling", name: "Teeling Small Batch", category: "irish", region: "Dublin",
    ageYears: null, abv: 46, caskTypes: ["ex-bourbon", "rum"], msrp: 40, avgPrice: 38,
    description: "Rum-cask-finished Dublin blend; tropical, vanilla-forward, and lively.",
    flavorProfile: fp({ fruity: 6, sweet: 6, grain: 4, spicy: 3, woody: 2 }), aliases: ["Teeling"] },
  { id: "teeling-single-malt", distilleryId: "teeling", name: "Teeling Single Malt", category: "irish", region: "Dublin",
    ageYears: null, abv: 46, caskTypes: ["sherry", "port", "madeira", "white burgundy", "cabernet"], msrp: 60, avgPrice: 55,
    description: "Five-wine-cask vatting; orchard and tropical fruit with a dry finish.",
    flavorProfile: fp({ fruity: 7, sweet: 5, floral: 3, grain: 3, woody: 3 }), aliases: [] },
  { id: "tullamore-dew", distilleryId: "tullamore", name: "Tullamore D.E.W.", category: "irish", region: "County Offaly",
    ageYears: null, abv: 40, caskTypes: ["ex-bourbon", "sherry"], msrp: 30, avgPrice: 25,
    description: "Triple-blend, triple-distilled crowd-pleaser; lemon, malt, and mild oak.",
    flavorProfile: fp({ grain: 5, fruity: 4, sweet: 4, floral: 2, woody: 2 }), aliases: ["Tully"] },
  { id: "tyrconnell", distilleryId: "kilbeggan", name: "The Tyrconnell Single Malt", category: "irish", region: "County Louth",
    ageYears: null, abv: 43, caskTypes: ["ex-bourbon"], msrp: 35, avgPrice: 32,
    description: "Double-distilled Irish malt; orange blossom, honey, and biscuit.",
    flavorProfile: fp({ fruity: 5, floral: 4, sweet: 5, grain: 4, woody: 2 }), aliases: [] },
  { id: "connemara-peated", distilleryId: "kilbeggan", name: "Connemara Peated Single Malt", category: "irish", region: "County Louth",
    ageYears: null, abv: 40, caskTypes: ["ex-bourbon"], msrp: 45, avgPrice: 40,
    description: "Ireland's signature peated malt; soft turf smoke over honeyed barley.",
    flavorProfile: fp({ peaty: 6, sweet: 5, fruity: 4, grain: 4, floral: 2 }), aliases: ["Connemara"] },

  // =========================================================================
  // JAPANESE
  // =========================================================================
  { id: "yamazaki-12", distilleryId: "suntory", name: "Yamazaki 12", category: "japanese", region: "Osaka",
    ageYears: 12, abv: 43, caskTypes: ["ex-bourbon", "sherry", "mizunara oak"], msrp: 185, avgPrice: 160,
    description: "Japan's first single malt: ripe persimmon, honey, and incense-like mizunara spice.",
    flavorProfile: fp({ fruity: 7, sweet: 6, floral: 4, woody: 4, spicy: 3, grain: 2 }), aliases: ["Yama 12"] },
  { id: "yamazaki-18", distilleryId: "suntory", name: "Yamazaki 18", category: "japanese", region: "Osaka",
    ageYears: 18, abv: 43, caskTypes: ["sherry", "mizunara oak"], msrp: 450, avgPrice: 1100,
    description: "Deep sherried Japanese icon; dried fruit, sandalwood, and dark chocolate.",
    flavorProfile: fp({ fruity: 8, sweet: 7, woody: 7, spicy: 4, feinty: 2 }), aliases: ["Yama 18"] },
  { id: "hakushu-12", distilleryId: "suntory", name: "Hakushu 12", category: "japanese", region: "Yamanashi",
    ageYears: 12, abv: 43, caskTypes: ["ex-bourbon", "lightly peated malt"], msrp: 185, avgPrice: 170,
    description: "The forest distillery's green, herbal malt; cucumber, mint, and a whisper of smoke.",
    flavorProfile: fp({ floral: 6, fruity: 5, peaty: 3, grain: 4, sweet: 4 }), aliases: ["Haku 12"] },
  { id: "hakushu-18", distilleryId: "suntory", name: "Hakushu 18", category: "japanese", region: "Yamanashi",
    ageYears: 18, abv: 43, caskTypes: ["ex-bourbon"], msrp: 450, avgPrice: 900,
    description: "Mature mountain-forest malt; melon, smoked herbs, and honeyed oak.",
    flavorProfile: fp({ fruity: 6, floral: 5, peaty: 3, sweet: 5, woody: 5 }), aliases: [] },
  { id: "hibiki-harmony", distilleryId: "suntory", name: "Hibiki Japanese Harmony", category: "japanese", region: "Japan",
    ageYears: null, abv: 43, caskTypes: ["ex-bourbon", "sherry", "mizunara oak"], msrp: 100, avgPrice: 90,
    description: "Suntory's flagship blend in the 24-facet bottle; orange peel, white chocolate, and rose.",
    flavorProfile: fp({ fruity: 6, floral: 5, sweet: 6, grain: 3, woody: 3 }), aliases: ["Hibiki", "Harmony"] },
  { id: "hibiki-21", distilleryId: "suntory", name: "Hibiki 21", category: "japanese", region: "Japan",
    ageYears: 21, abv: 43, caskTypes: ["ex-bourbon", "sherry", "mizunara oak"], msrp: 500, avgPrice: 1400,
    description: "Repeat world's-best-blended winner; layered dried fruit, incense, and silk.",
    flavorProfile: fp({ fruity: 8, sweet: 7, woody: 6, floral: 4, spicy: 3, feinty: 1 }), aliases: [] },
  { id: "suntory-toki", distilleryId: "suntory", name: "Suntory Toki", category: "japanese", region: "Japan",
    ageYears: null, abv: 43, caskTypes: ["ex-bourbon", "refill oak"], msrp: 40, avgPrice: 35,
    description: "Highball-first blend of Hakushu, Yamazaki, and Chita grain; green apple and honey.",
    flavorProfile: fp({ grain: 5, fruity: 4, sweet: 4, floral: 3, woody: 2 }), aliases: ["Toki"] },
  { id: "yoichi-single-malt", distilleryId: "nikka", name: "Nikka Yoichi Single Malt", category: "japanese", region: "Hokkaido",
    ageYears: null, abv: 45, caskTypes: ["ex-bourbon", "sherry"], msrp: 90, avgPrice: 85,
    description: "Coal-fired coastal Hokkaido malt; smoky, briny, and fruit-laced.",
    flavorProfile: fp({ peaty: 5, fruity: 5, sweet: 4, woody: 4, feinty: 2, grain: 2 }), aliases: ["Yoichi"] },
  { id: "miyagikyo-single-malt", distilleryId: "nikka", name: "Nikka Miyagikyo Single Malt", category: "japanese", region: "Sendai",
    ageYears: null, abv: 45, caskTypes: ["sherry", "ex-bourbon"], msrp: 90, avgPrice: 85,
    description: "Yoichi's elegant sibling; apple blossom, sherry fruit, and soft malt.",
    flavorProfile: fp({ fruity: 6, floral: 5, sweet: 5, grain: 3, woody: 3 }), aliases: ["Miyagikyo"] },
  { id: "nikka-from-the-barrel", distilleryId: "nikka", name: "Nikka From the Barrel", category: "japanese", region: "Japan",
    ageYears: null, abv: 51.4, caskTypes: ["refill oak"], msrp: 65, avgPrice: 60,
    description: "Densely packed high-proof blend in the little square bottle; caramel, winter spice, and orange.",
    flavorProfile: fp({ sweet: 6, spicy: 5, fruity: 5, woody: 4, grain: 3, feinty: 1 }), aliases: ["NFTB"] },
  { id: "nikka-coffey-grain", distilleryId: "nikka", name: "Nikka Coffey Grain", category: "japanese", region: "Japan",
    ageYears: null, abv: 45, caskTypes: ["ex-bourbon"], msrp: 75, avgPrice: 70,
    description: "Corn whisky from vintage Coffey stills; bourbon-like vanilla, coconut, and tropical fruit.",
    flavorProfile: fp({ sweet: 7, grain: 5, fruity: 5, woody: 3, floral: 1 }), aliases: ["Coffey Grain"] },
  { id: "taketsuru-pure-malt", distilleryId: "nikka", name: "Nikka Taketsuru Pure Malt", category: "japanese", region: "Japan",
    ageYears: null, abv: 43, caskTypes: ["ex-bourbon", "sherry"], msrp: 100, avgPrice: 90,
    description: "Yoichi-Miyagikyo vatted malt honoring Nikka's founder; balanced fruit, malt, and faint smoke.",
    flavorProfile: fp({ fruity: 6, sweet: 5, grain: 4, peaty: 2, woody: 3, floral: 2 }), aliases: ["Taketsuru"] },
  { id: "ichiros-malt-and-grain", distilleryId: "chichibu", name: "Ichiro's Malt & Grain", category: "japanese", region: "Saitama",
    ageYears: null, abv: 46.5, caskTypes: ["ex-bourbon", "sherry"], msrp: 110, avgPrice: 100,
    description: "Chichibu-anchored 'world blended whisky'; honeyed citrus and gentle oak.",
    flavorProfile: fp({ fruity: 5, sweet: 6, grain: 4, floral: 3, woody: 3 }), aliases: ["Malt & Grain"] },
  { id: "ichiros-malt-mwr", distilleryId: "chichibu", name: "Ichiro's Malt Mizunara Wood Reserve", category: "japanese", region: "Saitama",
    ageYears: null, abv: 46, caskTypes: ["mizunara oak"], msrp: 130, avgPrice: 150,
    description: "Vatted malt married in Japanese mizunara oak; sandalwood, coconut, and temple incense.",
    flavorProfile: fp({ woody: 6, fruity: 5, floral: 4, sweet: 5, spicy: 4 }), aliases: ["MWR"] },

  // =========================================================================
  // CANADIAN
  // =========================================================================
  { id: "crown-royal", distilleryId: "crown-royal", name: "Crown Royal Deluxe", category: "canadian", region: "Manitoba",
    ageYears: null, abv: 40, caskTypes: ["refill oak"], msrp: 30, avgPrice: 28,
    description: "The purple-bag standard; creamy vanilla, caramel, and soft rye spice.",
    flavorProfile: fp({ sweet: 6, grain: 5, fruity: 3, spicy: 3, woody: 3 }), aliases: ["Crown"] },
  { id: "crown-royal-northern-harvest", distilleryId: "crown-royal", name: "Crown Royal Northern Harvest Rye", category: "canadian", region: "Manitoba",
    ageYears: null, abv: 45, caskTypes: ["refill oak"], msrp: 35, avgPrice: 32,
    description: "The 90%-rye blend that won World Whisky of the Year in 2016; baking spice over butterscotch.",
    flavorProfile: fp({ spicy: 6, sweet: 6, grain: 4, fruity: 3, floral: 2, woody: 3 }), aliases: ["Northern Harvest", "CRNH"] },
  { id: "canadian-club-1858", distilleryId: "hiram-walker", name: "Canadian Club 1858", category: "canadian", region: "Ontario",
    ageYears: null, abv: 40, caskTypes: ["refill oak"], msrp: 20, avgPrice: 18,
    description: "The classic 'CC' highball whisky; light, clean barley-corn sweetness.",
    flavorProfile: fp({ grain: 6, sweet: 5, fruity: 2, woody: 2, spicy: 2 }), aliases: ["CC", "Canadian Club"] },
  { id: "canadian-club-12", distilleryId: "hiram-walker", name: "Canadian Club Classic 12", category: "canadian", region: "Ontario",
    ageYears: 12, abv: 40, caskTypes: ["refill oak"], msrp: 25, avgPrice: 22,
    description: "Twelve-year CC with deeper toffee and dried fruit.",
    flavorProfile: fp({ sweet: 6, grain: 5, woody: 4, fruity: 3, spicy: 2 }), aliases: ["CC 12"] },
  { id: "jp-wisers-18", distilleryId: "hiram-walker", name: "J.P. Wiser's 18", category: "canadian", region: "Ontario",
    ageYears: 18, abv: 40, caskTypes: ["refill oak"], msrp: 70, avgPrice: 65,
    description: "Long-aged corn-forward Canadian; toasted oak, apple, and toffee elegance.",
    flavorProfile: fp({ woody: 6, sweet: 6, grain: 4, fruity: 4, spicy: 2, feinty: 1 }), aliases: ["Wisers 18"] },
  { id: "lot-40", distilleryId: "hiram-walker", name: "Lot No. 40 Rye", category: "canadian", region: "Ontario",
    ageYears: null, abv: 43, caskTypes: ["new charred oak"], mashBill: "100% rye (pot still)", msrp: 40, avgPrice: 38,
    description: "Pot-distilled 100% rye — the Canadian rye enthusiasts evangelize; rye bread, clove, and dark caramel.",
    flavorProfile: fp({ spicy: 7, grain: 5, sweet: 5, woody: 4, floral: 3, fruity: 2 }), aliases: ["Lot 40"] },
  { id: "pike-creek-10", distilleryId: "hiram-walker", name: "Pike Creek 10 Rum Barrel", category: "canadian", region: "Ontario",
    ageYears: 10, abv: 42, caskTypes: ["refill oak", "rum"], msrp: 35, avgPrice: 32,
    description: "Rum-finished Canadian; brown sugar, banana, and vanilla.",
    flavorProfile: fp({ sweet: 7, fruity: 5, grain: 4, woody: 3, spicy: 2 }), aliases: ["Pike Creek"] },
  { id: "alberta-premium-cask-strength", distilleryId: "alberta-distillers", name: "Alberta Premium Cask Strength Rye", category: "canadian", region: "Alberta",
    ageYears: null, abv: 65.1, caskTypes: ["new charred oak", "refill oak"], mashBill: "100% rye", msrp: 70, avgPrice: 80,
    description: "Jim Murray's 2021 World Whisky of the Year; blistering 100% rye with dill, caramel, and fire.",
    flavorProfile: fp({ spicy: 8, sweet: 6, woody: 5, grain: 4, floral: 3, feinty: 1 }), aliases: ["APCS", "Alberta Premium CS"] },

  // =========================================================================
  // AMERICAN SINGLE MALT & OTHER AMERICAN
  // =========================================================================
  { id: "westland-american-oak", distilleryId: "westland", name: "Westland American Oak", category: "american-single-malt", region: "Washington",
    ageYears: null, abv: 46, caskTypes: ["new american oak", "ex-bourbon"], msrp: 70, avgPrice: 65,
    description: "Five-malt Seattle single malt; chocolate malt, stewed plum, and coffee.",
    flavorProfile: fp({ grain: 6, sweet: 6, fruity: 4, woody: 4, spicy: 2 }), aliases: ["Westland"] },
  { id: "westland-peated", distilleryId: "westland", name: "Westland Peated", category: "american-single-malt", region: "Washington",
    ageYears: null, abv: 46, caskTypes: ["new american oak", "ex-bourbon"], msrp: 90, avgPrice: 85,
    description: "Pacific Northwest take on peat; campfire smoke over chocolate-malt richness.",
    flavorProfile: fp({ peaty: 6, grain: 5, sweet: 5, fruity: 3, woody: 4 }), aliases: [] },
  { id: "stranahans-original", distilleryId: "stranahans", name: "Stranahan's Original", category: "american-single-malt", region: "Colorado",
    ageYears: 4, abv: 47, caskTypes: ["new charred oak"], msrp: 60, avgPrice: 55,
    description: "Rocky Mountain single malt aged in new charred oak; toffee, malt ball, and pine.",
    flavorProfile: fp({ grain: 5, sweet: 6, woody: 5, fruity: 3, spicy: 2 }), aliases: ["Stranahans"] },
  { id: "balcones-texas-single-malt", distilleryId: "balcones", name: "Balcones Texas Single Malt", category: "american-single-malt", region: "Texas",
    ageYears: null, abv: 53, caskTypes: ["new american oak", "refill oak"], msrp: 80, avgPrice: 75,
    description: "Texas-heat-matured Golden Promise malt; ripe banana, toasted sugar, and heavy oak.",
    flavorProfile: fp({ sweet: 7, fruity: 6, woody: 6, grain: 4, spicy: 3 }), aliases: ["Balcones 1"] },
  { id: "westward-single-malt", distilleryId: "westward", name: "Westward American Single Malt", category: "american-single-malt", region: "Oregon",
    ageYears: null, abv: 45, caskTypes: ["new american oak"], msrp: 90, avgPrice: 80,
    description: "Ale-yeast fermentation gives stone fruit and brownie batter over gentle oak.",
    flavorProfile: fp({ fruity: 5, grain: 5, sweet: 6, woody: 4, spicy: 2 }), aliases: ["Westward"] },
  { id: "jack-daniels-old-no-7", distilleryId: "jack-daniels", name: "Jack Daniel's Old No. 7", category: "american-other", region: "Tennessee",
    ageYears: null, abv: 40, caskTypes: ["new charred oak"], mashBill: "80% corn, 12% malted barley, 8% rye", msrp: 28, avgPrice: 25,
    description: "Charcoal-mellowed Tennessee icon; banana, caramel, and light char.",
    flavorProfile: fp({ sweet: 6, fruity: 4, grain: 4, woody: 4, spicy: 2, feinty: 1 }), aliases: ["JD", "Old No. 7", "Jack"] },
  { id: "jack-daniels-sbbp", distilleryId: "jack-daniels", name: "Jack Daniel's Single Barrel Barrel Proof", category: "american-other", region: "Tennessee",
    ageYears: null, abv: 65, caskTypes: ["new charred oak"], mashBill: "80% corn, 12% malted barley, 8% rye", msrp: 70, avgPrice: 70,
    description: "Uncut single barrels that converted the enthusiast crowd; banana bread, dark caramel, and oak spice.",
    flavorProfile: fp({ sweet: 8, woody: 7, fruity: 5, spicy: 5, grain: 2, feinty: 1 }), aliases: ["JDSBBP", "JD Barrel Proof"] },
  { id: "george-dickel-bib-13", distilleryId: "george-dickel", name: "George Dickel Bottled in Bond 13 Year", category: "american-other", region: "Tennessee",
    ageYears: 13, abv: 50, caskTypes: ["new charred oak"], mashBill: "84% corn, 8% rye, 8% malted barley", msrp: 45, avgPrice: 45,
    description: "Aged Tennessee bond at a bargain; buttered corn, vitamin-y minerality, and maple.",
    flavorProfile: fp({ sweet: 6, woody: 6, grain: 4, fruity: 3, feinty: 3, spicy: 3 }), aliases: ["Dickel BiB"] },
  { id: "balcones-baby-blue", distilleryId: "balcones", name: "Balcones Baby Blue Corn Whisky", category: "american-other", region: "Texas",
    ageYears: null, abv: 46, caskTypes: ["refill oak"], mashBill: "100% roasted blue corn", msrp: 45, avgPrice: 42,
    description: "Roasted blue-corn whisky; buttered popcorn, honey, and chile warmth.",
    flavorProfile: fp({ grain: 7, sweet: 6, spicy: 3, woody: 3, fruity: 2 }), aliases: ["Baby Blue"] },

  // =========================================================================
  // WORLD
  // =========================================================================
  { id: "kavalan-classic", distilleryId: "kavalan", name: "Kavalan Classic Single Malt", category: "world", region: "Taiwan",
    ageYears: null, abv: 40, caskTypes: ["ex-bourbon", "sherry"], msrp: 100, avgPrice: 90,
    description: "Sub-tropical Taiwanese malt; mango, honey, and vanilla in fast-forward maturity.",
    flavorProfile: fp({ fruity: 7, sweet: 6, floral: 3, woody: 3, grain: 2 }), aliases: ["Kavalan"] },
  { id: "kavalan-solist-oloroso", distilleryId: "kavalan", name: "Kavalan Solist Oloroso Sherry", category: "world", region: "Taiwan",
    ageYears: null, abv: 57.8, caskTypes: ["oloroso sherry"], msrp: 320, avgPrice: 300,
    description: "Cask-strength single-cask sherry monster; fig jam, dark chocolate, and tropical depth.",
    flavorProfile: fp({ fruity: 9, sweet: 8, woody: 5, spicy: 4, feinty: 2 }), aliases: ["Solist", "Solist Sherry"] },
  { id: "amrut-fusion", distilleryId: "amrut", name: "Amrut Fusion", category: "world", region: "India",
    ageYears: null, abv: 50, caskTypes: ["ex-bourbon", "new oak"], msrp: 85, avgPrice: 75,
    description: "Indian and peated Scottish barley fused; barley sugar, mango, and gentle smoke.",
    flavorProfile: fp({ fruity: 6, sweet: 5, peaty: 4, grain: 4, spicy: 4, woody: 3 }), aliases: ["Fusion"] },
  { id: "penderyn-madeira", distilleryId: "penderyn", name: "Penderyn Madeira Finish", category: "world", region: "Wales",
    ageYears: null, abv: 46, caskTypes: ["ex-bourbon", "madeira"], msrp: 75, avgPrice: 70,
    description: "Welsh single malt off the Faraday still; sultana, cream toffee, and citrus.",
    flavorProfile: fp({ fruity: 6, sweet: 6, floral: 3, grain: 3, woody: 3 }), aliases: ["Penderyn"] },
  { id: "starward-nova", distilleryId: "starward", name: "Starward Nova", category: "world", region: "Australia",
    ageYears: null, abv: 41, caskTypes: ["australian red wine"], msrp: 65, avgPrice: 55,
    description: "Melbourne malt matured fully in shiraz barrels; red berries, banana, and soft tannin.",
    flavorProfile: fp({ fruity: 7, sweet: 5, grain: 3, woody: 3, spicy: 3 }), aliases: ["Nova"] },
];
