// Bakes the server origin into the bundled offline shell, then runs `cap sync`
// so the native projects pick up config and plugin changes.
//
//   CAP_SERVER_URL=https://app.whaikey.com pnpm native:sync
import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { configProblems, repoRoot, serverUrl, shellDir } from "./native-config.mjs";

const problems = configProblems({ requireServer: false });
if (problems.length > 0) {
  console.error("✗ Native config is not ready:");
  for (const problem of problems) console.error(`  • ${problem}`);
  process.exit(1);
}

const url = serverUrl();

// The shell's "Try again" button needs somewhere to go, and Capacitor gives an
// error page no way to ask what the configured server was — so write it in.
// Generated, therefore gitignored.
writeFileSync(
  path.join(shellDir, "config.js"),
  `// Generated by scripts/native-sync.mjs — do not edit.\n` +
    `window.__WHAIKEY_SERVER_URL__ = ${JSON.stringify(url)};\n`,
  "utf8",
);
console.log(url ? `• Shell will reconnect to ${url}` : "• No server URL — shell will say so");

const hasPlatform =
  existsSync(path.join(repoRoot, "ios")) || existsSync(path.join(repoRoot, "android"));
if (!hasPlatform) {
  console.log("• No native platforms yet — run `pnpm native:add:ios` / `pnpm native:add:android`.");
  console.log("✓ Shell prepared.");
  process.exit(0);
}

execFileSync("pnpm", ["exec", "cap", "sync"], { cwd: repoRoot, stdio: "inherit" });
console.log("✓ Native projects synced.");
